Get Default messages of chats
pedroslopez/whatsapp-web.js pull request #1015
Opened 2021-11-27 06:22 UTC by AxeemHaider

This is related to #1014 

Removing static limit from `fetchMessages()` and it solve things. Now if you don't provide any `limit` then it will get default messages.

2021-12-13 02:15 UTC, pedroslopez requested changes
This looks ok to me, though noting that this would change the behavior to not fetch anything and only return the available messages my default, unless a limit is specified. I think this makes sense and is in line with what most people would want.

Let's make sure that the docs reflect the new behavior accurately by updating the jsdoc strings and typings. We'll need to make relevant changes to `MessageSearchOptions` here:

https://github.com/pedroslopez/whatsapp-web.js/blob/46ba9c5e9aa0bc4de5eba1a561e7f4ef8050084a/index.d.ts#L910-L917

2021-12-13 02:15 UTC, pedroslopez commented on src/structures/Chat.js
> +     * @param {Number} [searchOptions.limit] The amount of messages to return. Note that the actual number of returned messages may be smaller if there aren't enough messages in the conversation. Set
```suggestion
     * @param {Number} [searchOptions.limit] The amount of messages to return. If no limit is specified, the available messages will be returned. Note that the actual number of returned messages may be smaller if there aren't enough messages in the conversation. Set this to Infinity to load all messages.
```

2022-02-06 23:12 UTC, PurpShell approved these changes

2022-02-06 23:26 UTC, pedroslopez approved these changes

2022-02-06 23:27 UTC, merged