getNumberIdSolvedMD
pedroslopez/whatsapp-web.js pull request #1142
Opened 2022-01-27 03:58 UTC by KeruMx

handler.withDeviceProtocol() returned number of connections if deviceList ==0 is not a registered whatsapp user

2022-01-27 03:59 UTC, KeruMx commented
For #889,

2022-01-27 08:02 UTC, mihazavr commented
> For #889,

not works for me. looks like it returns nothing at all

2022-01-27 12:54 UTC, jaovitubr commented
Working!

2022-01-27 15:47 UTC, KeruMx commented
> > For #889,
> 
> not works for me. looks like it returns nothing at all

what is your error?

2022-01-27 15:51 UTC, fm1randa commented
> > > For #889,
> > 
> > 
> > not works for me. looks like it returns nothing at all
> 
> what is your error?

here it's loading infinitely

2022-01-27 16:08 UTC, KeruMx commented
> > what is your error?
> 
> here it's loading infinitely

can you put your code, to try replicate

2022-01-27 16:48 UTC, PurpShell requested changes
Please apply the following changes

2022-01-27 16:48 UTC, PurpShell commented on src/Client.js
> +                return result.list[0].devices.deviceList.length>0;
```suggestion
                return result.list[0].devices.deviceList.length > 0;
```
clean the code

2022-01-27 16:48 UTC, PurpShell commented on src/util/Injected.js
> +                return id
```suggestion
                return id;
```
 missing semicolon

2022-01-27 16:55 UTC, PurpShell commented on src/util/Injected.js
> +            if (result.list[0].devices.deviceList.length>0) {
```suggestion
            if (result.list[0].devices.deviceList.length > 0) {
```

2022-01-27 16:56 UTC, purpshell approved these changes
lgtm

2022-01-27 16:57 UTC, merged

2022-01-27 19:23 UTC, fm1randa commented
> can you put your code, to try replicate

```ts
import { Client } from "whatsapp-web.js";

async function getChatID(client: Client, number: string) {
	try {
		const numberId = await client.getNumberId(number); // app get stuck here
		return numberId._serialized;
	} catch (error) {
		throw new Error(
			`Couldn't find chatID for number ${number}. Make sure the number is registered in Whatsapp or the number is in correct format (+5521987654321).\n\n${error}`
		);
	}
}

export default getChatID;

```

2022-01-27 21:24 UTC, KeruMx commented
> > can you put your code, to try replicate
> 
> ```ts
> import { Client } from "whatsapp-web.js";
> 
> async function getChatID(client: Client, number: string) {
> 	try {
> 		const numberId = await client.getNumberId(number); // app gets stuck here
> 		return numberId._serialized;
> 	} catch (error) {
> 		throw new Error(
> 			`Couldn't find chatID for number ${number}. Make sure the number is registered in Whatsapp or the number is in correct format (+5521987654321).\n\n${error}`
> 		);
> 	}
> }
> 
> export default getChatID;
> ```

Only works for MultiDevice Branch, are you using this branch?

2022-01-27 23:27 UTC, fm1randa commented
> Only works for MultiDevice Branch, are you using this branch?
I was using your branch `KeruMx:getNumberIdMD` and after the merge, at `pedroslopez:multidevice` got the same result :(

2022-01-28 00:30 UTC, ReniDelonzek commented
I tried this and it didn't work for me either.

2022-01-28 12:29 UTC, Shvan11 commented
getNumberID() is not working for me too, it is stuck at this line:

`` handler = handler.withUser((new window.Store.USyncUser).withId(id), handler.withDeviceProtocol(), 1);
            let result = await handler.execute();``

2022-01-28 13:06 UTC, fm1randa commented
> getNumberID() is not working for me too, it is stuck at this line:
> 
> handler = handler.withUser((new window.Store.USyncUser).withId(id), handler.withDeviceProtocol(), 1);
> 
> ```
>         let result = await handler.execute();`
> ```

same here.

2022-01-28 18:10 UTC, mihazavr commented
Any ideas how to check if number registered another way?

2022-01-31 14:44 UTC, alissonbezerra commented
> > getNumberID() is not working for me too, it is stuck at this line:
> > handler = handler.withUser((new window.Store.USyncUser).withId(id), handler.withDeviceProtocol(), 1);
> > ```
> >         let result = await handler.execute();`
> > ```
> 
> same here.

Seems like the problem is in `Client.js`. 

```
        if(!number.startsWith('+')) {
            number = '+' + number;
        }
```

When I removed those lines above from the function `getNumberId`, the Promise was returned successfully.

2022-01-31 14:49 UTC, mihazavr commented
> > > getNumberID() is not working for me too, it is stuck at this line:
> > > handler = handler.withUser((new window.Store.USyncUser).withId(id), handler.withDeviceProtocol(), 1);
> > > ```
> > >         let result = await handler.execute();`
> > > ```
> > 
> > 
> > same here.
> 
> Seems like the problem is in `Client.js`.
> 
> ```
>         if(!number.startsWith('+')) {
>             number = '+' + number;
>         }
> ```
> 
> When I removed those lines above from the function `getNumberId`, the Promise was returned successfully.

It works! Thank you!

2022-02-01 02:10 UTC, ReniDelonzek commented
Hello guys, I submitted a [PR](https://github.com/pedroslopez/whatsapp-web.js/pull/1159) applying the fix, thank you @alissonbezerra  for pointing out the problem

2022-02-02 18:56 UTC, mahmouds12 commented
@ReniDelonzek 
client.getNumberId() is still not working as expected. It works correctly for **correct whatsapp numbers**, but if the number is incorrect, it will stuck forever

2022-02-06 23:06 UTC, PurpShell commented
> @ReniDelonzek 
> client.getNumberId() is still not working as expected. It works correctly for **correct whatsapp numbers**, but if the number is incorrect, it will stuck forever

Then we can place a timeout