Add "fromMe" option to fetchMessages
pedroslopez/whatsapp-web.js pull request #1444
Opened 2022-05-08 19:14 UTC by roigreenberg

I added an option to get only messages from the bot, or not from the bot.
This is needed in some edge case where there is a message from the bot after calling "countUnread". otherwise, fetchMessages will return the bot message instead a unread message.

2022-07-07 14:52 UTC, PurpShell requested changes
Hey! please rebase your PR and remove anything not related to the "fromMe" option, thanks. will approve after that

2022-07-10 12:42 UTC, roigreenberg commented
@PurpShell I removed any unrelated changes, I hope that is enough.

2022-08-09 09:26 UTC, PurpShell approved these changes

2022-08-09 09:26 UTC, PurpShell commented on src/structures/Chat.js
> +                    if (searchOptions.fromMe !== undefined && m.id.fromMe !== searchOptions.fromMe) {
```suggestion
                    if (searchOptions.fromMe && m.id.fromMe !== searchOptions.fromMe) {
```

2022-08-09 09:27 UTC, PurpShell commented
lgtm

2022-08-09 14:16 UTC, tuyuribr commented on src/structures/Chat.js
> +                    if (searchOptions.fromMe && m.id.fromMe !== searchOptions.fromMe) {
LGTM but put searchOptions inside the inner if. (searchOptions && searchOptions.fromMe && .... )

2022-08-09 14:18 UTC, tuyuribr commented
Also don't forget to document it in **index.d.ts**

2022-08-11 18:55 UTC, tuyuribr approved these changes

2022-08-14 15:30 UTC, merged