Fix of fetchMessages
pedroslopez/whatsapp-web.js pull request #1480
Opened 2022-06-01 07:58 UTC by jurajmatus

`chat.loadEarlierMsgs()` returns an empty array instead of null|undefined. Because of this it lead to an infinite cycle that never ended.

2022-06-02 11:27 UTC, su-chang approved these changes
LGTM

2022-06-06 08:53 UTC, shirser121 approved these changes
LGTM

2022-06-07 00:30 UTC, mojila approved these changes

2022-06-10 03:55 UTC, pedroslopez requested changes
Thanks for the fix! Makes sense to me, just one note on proper compatibility with older node versions.

2022-06-10 03:55 UTC, pedroslopez commented on src/structures/Chat.js
> +                    if (!loadedMessages?.length) break;
Please avoid using features that are not available in node v12 since we still support this version (optional chaining is not available)

2022-06-14 04:22 UTC, pedroslopez approved these changes

2022-06-14 04:22 UTC, merged