Fix new version
pedroslopez/whatsapp-web.js pull request #1503
Opened 2022-06-08 20:49 UTC by shirser121

2022-06-09 00:36 UTC, LucianoHanna approved these changes
Looks good to me

2022-06-09 05:54 UTC, RakSrinaNa approved these changes

2022-06-09 11:36 UTC, jtourisNS approved these changes

2022-06-09 14:22 UTC, tuyuribr approved these changes

2022-06-09 14:23 UTC, aliyss approved these changes
lgtm

2022-06-09 16:47 UTC, jurajmatus commented
`chat.preload` is a synchronous method which only spawns `loadEarlierMsgs` and returns immediately, which results in always having 1 message loaded from chat

I suggest to apply this patch in addition to the changes here: https://github.com/instea/whatsapp-web.js/commit/36882c33a6b785a36dc6a88e4a52889e78268c54

2022-06-09 22:04 UTC, XxQuickSilverZz commented
> `chat.preload` is a synchronous method which only spawns `loadEarlierMsgs` and returns immediately, which results in always having 1 message loaded from chat
> 
> I suggest to apply this patch in addition to the changes here: [instea@36882c3](https://github.com/instea/whatsapp-web.js/commit/36882c33a6b785a36dc6a88e4a52889e78268c54)

i still get only the last message. Changed the lines above...

2022-06-09 23:09 UTC, Yuri-Lima approved these changes
Fine

2022-06-09 23:28 UTC, Yuri-Lima requested changes

2022-06-09 23:28 UTC, Yuri-Lima commented on src/Client.js
> +            if (window.Store.Chat._models.length > MAX_PIN_COUNT) {
what about that?
`
window.Store.Chat.models.length ? window.Store.Chat.models.length : window.Store.Chat._models.length
`

2022-06-09 23:28 UTC, Yuri-Lima commented on src/Client.js
> +            const labelItems = label.labelItemCollection._models;
Same here
`
const labelItems = label.labelItemCollection.models || label.labelItemCollection._models;
`

2022-06-09 23:28 UTC, Yuri-Lima commented on src/util/Injected.js
> +        const chats = window.Store.Chat._models;
Same
`
const chats = window.Store.Chat.models || window.Store.Chat._models;
`

2022-06-09 23:28 UTC, Yuri-Lima commented on src/util/Injected.js
> +        const contacts = window.Store.Contact._models;
Same
`
const contacts = window.Store.Contact.models || window.Store.Contact._models;
`

2022-06-09 23:28 UTC, Yuri-Lima commented on src/util/Injected.js
> +        const labels = window.Store.Label._models;
Same
`
const labels = window.Store.Label.models || window.Store.Label._models;
`

2022-06-10 02:49 UTC, LucianoHanna commented
> 



> after apply this patch, i got this error
> 
> ```
> Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'getContact')
>     at __puppeteer_evaluation_script__:2:34
>     at ExecutionContext._evaluateInternal (/src/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async ExecutionContext.evaluate (/src/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
>     at async Client.getContactById (/src/node_modules/whatsapp-web.js/src/Client.js:671:23)
>     at async /src/app.js:303:27
> ```
> 
> i think the right method is `getContacts`. or am i miss something ?

`return window.WWebJS.getContact(contactId);`

Error is probably at this line, I think it was because window.WWebJS is undefined.

Maybe there's another problem causing that. Others functions are not working in your app or just that function?

2022-06-10 03:04 UTC, abudawud commented
> after apply this patch, i got this error
> 
> ```
> Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'getContact')
>     at __puppeteer_evaluation_script__:2:34
>     at ExecutionContext._evaluateInternal (/src/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async ExecutionContext.evaluate (/src/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
>     at async Client.getContactById (/src/node_modules/whatsapp-web.js/src/Client.js:671:23)
>     at async /src/app.js:303:27
> ```
> 
> i think the right method is `getContacts`. or am i miss something ?

so sorry, this error just happened in my server. i test it on my local development it's working well

2022-06-10 03:40 UTC, pedroslopez approved these changes
Made a few changes to match whatsapp's internal usage. Thanks for the fix!

2022-06-10 03:41 UTC, merged