feat: [Updated] Loading screen listener with percent and message
pedroslopez/whatsapp-web.js pull request #1563
Opened 2022-07-01 19:38 UTC by tonbotfy

It will help a lot of people who need this whatsapp screen status.

When the screen is loading, the 'loading_screen' event is called with two parameters:
percent
message
![174875294-c06e1263-a5c8-4183-96a4-0fb6f25f8177](https://user-images.githubusercontent.com/106827778/176958876-bfc66c9a-72a6-4942-a72b-d1c99d3e4f80.png)

Updated from PR #1533 
Referenced by Issue #1556

2022-07-05 03:18 UTC, tonbotfy commented
> 

Hi! Yes it shows the real % of the whatsapp page. I could already see yes, it depends a lot on the cash of your machine with your cell phone.

2022-07-07 14:47 UTC, PurpShell approved these changes
looks really good to me, thanks for adding this

2022-07-07 14:49 UTC, PurpShell requested changes
fix eslint errors then I'll re-approve it

2022-07-07 19:13 UTC, tonbotfy commented
@PurpShell 
> fix eslint errors then I'll re-approve it

Done! 🥰

2022-07-08 20:20 UTC, jtourisNS commented on example.js
> +    puppeteer: { headless: true }
Just curious, why did you change this?

2022-07-08 20:34 UTC, jtouris approved these changes

2022-07-10 11:19 UTC, PurpShell approved these changes
Looks good

2022-07-11 03:30 UTC, tonbotfy commented
@pedroslopez can you marge/approve this pr?

2022-07-11 03:39 UTC, jtourisNS commented on example.js
> +    puppeteer: { headless: true }
@tonbotfy

2022-07-11 04:33 UTC, tonbotfy commented on example.js
> +    puppeteer: { headless: true }
@jtourisNS Done, my friend! 👍🏼

2022-07-12 21:10 UTC, stefanfuchs commented on index.d.ts
> +        /** Emitted when loading screen is appear */
```suggestion
        /** Emitted when loading screen is appearing */
```

2022-07-13 14:45 UTC, jtourisNS requested changes
Remember to also add the `LOADING_SCREEN` event on the Client enum Events - `index.d.ts #455`

2022-07-14 03:01 UTC, tonbotfy commented
> Remember to also add the `LOADING_SCREEN` event on the Client enum Events - `index.d.ts #455`

Done! 👍🏼

2022-07-22 19:49 UTC, tonbotfy commented
Any answer?

2022-08-09 14:50 UTC, tuyuribr approved these changes
LGTM! 
WAWEB: 2.2228.14

2022-08-09 14:54 UTC, tonbotfy commented
@tuyuribr Thanks. let's go to approval! 😍😍

2022-08-09 15:27 UTC, merged

2022-08-09 15:28 UTC, janke184 approved these changes