Feat: add message_reaction event
pedroslopez/whatsapp-web.js pull request #1619
Opened 2022-08-01 22:48 UTC by wictornogueira

Emits an event that is triggered whenever a reaction gets updated/created

2022-08-03 00:45 UTC, PurpShell approved these changes
ok I can't roast this wictor, I approve but I found one mistake hehheh

2022-08-03 00:45 UTC, PurpShell commented on src/Client.js
> +                 * @event Client#incoming_call
```suggestion
                 * @event Client#message_reaction
```

2022-08-09 15:00 UTC, tuyuribr requested changes
Hey @wictornogueira Really cool event, can you add an example on example.js ?

2022-08-09 15:32 UTC, PurpShell commented
@tuyuribr we plan to remove that file after the coverage of the [guide](https://wwebjs.dev/guide).

@wictornogueira merge conflicts

2022-08-09 19:08 UTC, tuyuribr approved these changes

2022-08-09 19:09 UTC, merged