Use getCommonGroups not contact
pedroslopez/whatsapp-web.js pull request #1623
Opened 2022-08-03 14:45 UTC by shirser121

Allow to use getCommonGroups for not contact numbers

2022-08-09 15:03 UTC, tuyuribr commented on src/Client.js
> +                const chatConstractor = window.Store.Contact.getModelsArray().find(c=>!c.isGroup).constructor;
Typo, everything else LGTM

2022-08-14 15:38 UTC, tuyuribr requested changes
typo

2022-08-14 15:56 UTC, shirser121 commented
> typo

What should I change?

2022-08-14 16:59 UTC, tuyuribr commented
> > typo
> 
> What should I change?

chatConstractor to chatConstructor

2022-08-15 11:12 UTC, PurpShell approved these changes
Approved

2022-08-18 16:18 UTC, tuyuribr approved these changes

2022-08-18 16:20 UTC, merged