add Error event propagation at InterfaceController
pedroslopez/whatsapp-web.js pull request #1662
Opened 2022-08-18 20:27 UTC by MuraraAllan

2022-08-19 13:20 UTC, iFraan approved these changes

2022-09-29 17:28 UTC, PurpShell approved these changes
:+1:

2022-10-15 15:34 UTC, tuyuribr requested changes
ESLint

2022-12-29 12:10 UTC, PurpShell commented
Hi. I suggest you use `.catch` instead.

2023-05-29 00:01 UTC, closed without merging