Fix GroupMetadata module
pedroslopez/whatsapp-web.js pull request #1789
Opened 2022-11-10 16:49 UTC by mrfelipemartins

# PR Details

This fixes GroupMetadata Modules in new version 2.2243.7

## Description

This will fix current errors in new WhatsApp Web Version since the GroupMetadata module was not being found with previous code.

## Related Issue

#1786 

## Types of changes

- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

2022-11-10 20:12 UTC, ricardoapaes approved these changes
I did the test here and this solution worked.

2022-11-10 20:26 UTC, SnzDev commented
I did the test here too and this solution worked

2022-11-10 20:27 UTC, SnzDev approved these changes

2022-11-11 00:32 UTC, diogolimas commented
can you disponible a patch version to install?

2022-11-11 02:17 UTC, imaperson1060 approved these changes
Tested, and this works.

2022-11-11 06:04 UTC, TiNaR71 commented
work

2022-11-11 06:04 UTC, TiNaR71 reviewed
work

2022-11-11 06:04 UTC, TiNaR71 approved these changes

2022-11-11 06:34 UTC, kahfidavy commented
I did the test here too and this solution worked

2022-11-11 09:33 UTC, Eonus21 approved these changes

2022-11-11 10:45 UTC, TemaSM approved these changes

2022-11-11 10:58 UTC, ubay887 approved these changes
Thanks for the solution.

2022-11-11 10:59 UTC, burkass commented
I did the test and it was success.

2022-11-11 12:30 UTC, fabiomello approved these changes

2022-11-11 13:10 UTC, janke184 approved these changes

2022-11-11 13:37 UTC, jaovitubr approved these changes
work

2022-11-11 13:40 UTC, brunogui0812 approved these changes

2022-11-11 13:40 UTC, DudaBoldt approved these changes

2022-11-11 13:42 UTC, GabrielFeMello approved these changes

2022-11-11 13:42 UTC, nistarok approved these changes

2022-11-11 13:44 UTC, steffany-cruz approved these changes

2022-11-11 15:35 UTC, minnigagustin approved these changes

2022-11-11 20:05 UTC, cbeltrangomez84 approved these changes
Urgent change

2022-11-11 20:13 UTC, Hanake0 approved these changes
Tested and working

2022-11-12 10:12 UTC, Absortian approved these changes
Working for me! Thanks

2022-11-12 11:31 UTC, yohanesgultom approved these changes
Works for me!

2022-11-12 12:14 UTC, Rakambda approved these changes

2022-11-12 12:51 UTC, Solo-it approved these changes
need ";" on the end

2022-11-12 12:56 UTC, Solo-it commented
#1795

2022-11-12 14:08 UTC, Soneji approved these changes

2022-11-12 14:35 UTC, crispyhook approved these changes

2022-11-12 16:03 UTC, tofers commented
After connecting, empty message messages arrive
![image](https://user-images.githubusercontent.com/6928045/201482988-aa989ef2-b1f3-4b5c-ad33-61fe3ae51988.png)

2022-11-12 17:10 UTC, douglasdf99 approved these changes

2022-11-12 19:42 UTC, RolandVrignon commented
It works for me too, but not completely.

There are problems in GroupMetaData after creation.

For example, here I have created a user who cannot be added to a group and the missingParticipants object is neither empty nor full.

 - When no participants are missing, missingParticipants is an empty object.
 - If there are missing participants, the missingParticipants object is something like { userWid: "5623xxxxx23@c.us" }.

Now it's still like in the attached image:

![Screenshot from 2022-11-12 20-34-00](https://user-images.githubusercontent.com/22148876/201491565-59f08154-05d5-4ec8-b503-70341c803543.png)

2022-11-12 19:49 UTC, RolandVrignon requested changes
It works for me too, but not completely.

There are problems in GroupMetaData after creation.

For example, here I have created groupchat with an user who cannot be added to a group and the missingParticipants object is neither empty nor full.

 - When no participants are missing, missingParticipants should be an empty object.
 - If there are missing participants, the missingParticipants object should be something like { userWid: "5623xxxxx23@c.us" }.

Now it's always like in the attached image :

![Screenshot from 2022-11-12 20-34-00](https://user-images.githubusercontent.com/22148876/201491565-59f08154-05d5-4ec8-b503-70341c803543.png)

2022-11-12 20:20 UTC, lfdelphino approved these changes
Tested and approved! Works as expected

2022-11-12 20:45 UTC, iTz1T4Y07 approved these changes

2022-11-12 22:19 UTC, peyretti commented
Resolveu para mim, voltou a funcionar.
Obrigado

2022-11-12 22:28 UTC, williamgranzotto commented
Working for me

2022-11-12 22:49 UTC, williamgranzotto approved these changes
It works for me. Could we get new release version?

2022-11-13 00:06 UTC, fauziave commented
for now it's connected and worked

2022-11-13 00:57 UTC, jeremyandes approved these changes
Works for me!

2022-11-13 02:23 UTC, gastonmanzano approved these changes

2022-11-13 02:24 UTC, gastonmanzano approved these changes
That works for me

2022-11-13 04:54 UTC, videjunior approved these changes
Funciona muito bem!

2022-11-13 05:25 UTC, devagarwal007 commented
Could any 2 people approve this who has the write access, since it is a bit urgent?

2022-11-13 05:26 UTC, devagarwal007 approved these changes
Looks good, working as expected.

2022-11-13 06:40 UTC, diegoavellanedat17 approved these changes

2022-11-13 11:29 UTC, PurpShell approved these changes

2022-11-13 11:30 UTC, PurpShell commented on src/util/Injected.js
> +    window.Store.GroupMetadata = window.mR.findModule('GroupMetadata')[0].default.GroupMetadata
```suggestion
    window.Store.GroupMetadata = window.mR.findModule('GroupMetadata')[0].default.GroupMetadata;
```

2022-11-13 11:32 UTC, PurpShell commented on src/util/Injected.js
> +    window.Store.GroupMetadata = window.mR.findModule('GroupMetadata')[0].default.GroupMetadata
commited

2022-11-13 11:35 UTC, Aliyss approved these changes
Lgtm

2022-11-13 11:36 UTC, merged

2022-11-13 13:27 UTC, tovab commented
@PurpShell When will this be released? 
Thank you!

2022-11-13 16:54 UTC, devagarwal007 commented
> Lgtm

@Aliyss @PurpShell When will this be released?

2022-11-13 18:37 UTC, mvenki2014 reviewed
I also got this error, i tried this problem has been fixed