fiat: load reactions in message
pedroslopez/whatsapp-web.js pull request #1897
Opened 2023-01-02 13:26 UTC by tofers

# PR Details

Loading reactions to a message

## Description
I think this is a necessary feature that I and other developers need.
Added downloading of reactions, if the message has them

NOTE: I didn't mean to single out a separate object, I hope I documented it correctly. Correct me if I did. 

## Related Issue

https://github.com/pedroslopez/whatsapp-web.js/issues/1548

## Motivation and Context

Reactions are going viral, and my clients are asking to see them not only in real time, but also when they view the messages.

## How Has This Been Tested

I've tested everything locally in my development environment.

## Types of changes

- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

2023-01-02 20:07 UTC, tuyuribr requested changes

2023-01-02 20:07 UTC, tuyuribr commented on src/structures/Message.js
> +        this.hasReaction = data.hasReaction;
this.hasReaction = data.hasReaction ? true : false

2023-01-16 05:16 UTC, Studentfr commented
Hi, there is a big necessity to use this feature for me. When it will be merged to the main?(https://github.com/pedroslopez/whatsapp-web.js/pull/1897)

2023-01-25 23:27 UTC, tuyuribr reviewed
LGTM! But we need testers here

2023-01-29 23:50 UTC, tuyuribr approved these changes

2023-04-01 13:58 UTC, PurpShell approved these changes

2023-04-01 14:03 UTC, merged