Added Proxy Authentication option in Client options constructor
pedroslopez/whatsapp-web.js pull request #1949
Opened 2023-01-21 14:05 UTC by danielR2001

## Description

Added Proxy Authentication option in Client options constructor.
```
async initialize() {
   //   code...
   if (this.options.proxyAuthentication !== undefined) {
      await page.authenticate(this.options.proxyAuthentication);
   }
   //   code...
}
```
      
## Related Issue

## Motivation and Context

I wanted to set up a proxy server in puppeteer but couldn't authenticate with it.

## How Has This Been Tested

## Types of changes

- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

2023-01-25 23:20 UTC, tuyuribr requested changes
Sounds like a cool feat but you can't change all files and submit in a PR, please remove any unrelated changes

2023-01-26 07:40 UTC, danielR2001 commented
All the changed files are the documentation auto generate 😅

2023-02-04 11:04 UTC, danielR2001 commented
I removed the documentation generate from the merge

2023-03-11 10:40 UTC, danielR2001 commented
why no one reviewing this pr?

2023-03-22 14:43 UTC, tuyuribr commented
Sorry for the delay, could you put an example in the example file and add the param to the index.d.ts ? Then I think we can merge

2023-04-01 19:17 UTC, tuyuribr requested changes
Index.d.ts

2023-04-09 13:32 UTC, PurpShell requested changes
requesting changes

2023-04-09 13:32 UTC, PurpShell commented on src/util/Injected.js
> +    window.Store.QueryExist = window.mR.findModule('queryExists')[0] ? window.mR.findModule('queryExists')[0].queryExists : window.mR.findModule('queryExist')[0].queryWidExists;
why do these exist? seperate into different branches and rebase

2023-04-18 23:44 UTC, PurpShell commented on src/util/Injected.js
> +    window.Store.MediaPrep = window.mR.findModule('prepRawMedia')[0];
```suggestion
    window.Store.MediaPrep = window.mR.findModule('MediaPrep')[0];
```

2023-04-18 23:45 UTC, PurpShell commented
Sorry, @danielR2001. I'll close this PR for your inactivity. #2143 has opened, credits will go to you

2023-04-18 23:45 UTC, closed without merging