fix(vcard): parse vcard module
pedroslopez/whatsapp-web.js pull request #1995
Opened 2023-02-12 14:40 UTC by CyrilLacroix

# PR Details

Fix for vCard parsing.

## Description

The module **vcardFromContactModel** doesn't contain _parseVcard_ and _vcardGetNameFromParsed_ functions anymore.
They can be found in the module **WA_BIZ_NAME**.

## Motivation and Context

The vCard was not display, the content of the vCard was sent to Whatsapp chat.

## How Has This Been Tested

Tested with a Bot, the vCard is now generated and displayed properly in Whatsapp.

## Types of changes

- [x] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

2023-02-12 17:22 UTC, tofers commented
#1994

2023-02-14 10:40 UTC, RC047 commented
thanks

2023-03-02 19:49 UTC, nathanfinger commented
Should this be working with multiple cards?

2023-03-22 15:05 UTC, tuyuribr requested changes, later dismissed
Please make ESList god happy

2023-05-14 17:04 UTC, themazim approved these changes
LGTM, works on ios, android and web.

2023-06-02 19:35 UTC, PurpShell commented
Remove all formatting changes

2023-06-05 15:17 UTC, frnndwrms commented
@CyrilLacroix 

Installing npm install git+https://github.com/CyrilLacroix/whatsapp-web.js.git

get a 

TypeError: data.id.id.substring is not a function

When is it going to be merge to master?

2023-08-07 20:57 UTC, shirser121 commented
Where we standing with this?

2023-08-12 13:31 UTC, RC047 commented
When this pull merge it? It works flawlessly @PurpShell @tuyuribr @shirser121

2023-09-03 10:55 UTC, RC047 approved these changes
I tested its work

2023-09-13 00:42 UTC, TuiNascimento approved these changes

2023-12-12 07:27 UTC, RC047 commented
@alechkos

2023-12-22 16:30 UTC, joweste commented
> I tested its work

Didn´t work to me

2024-01-12 02:06 UTC, alechkos commented
@CyrilLacroix 
Do you need help with a PR?

2024-01-17 01:39 UTC, khsoh commented
I tested the change and confirm that it fixes the problem.

2024-01-25 05:55 UTC, aksiuwaa commented
vcardGetNameFromParsed is no longer usable, I have switched to parsed.N[0].value.join(' ').trim()

2024-02-10 09:36 UTC, RemyBoy72 commented
> vcardGetNameFromParsed is no longer usable, I have switched to parsed.N[0].value.join(' ').trim()

Can you share all the code changes need to be placed?

2024-02-10 22:09 UTC, videjunior commented
> vcardGetNameFromParsed is no longer usable, I have switched to parsed.N[0].value.join(' ').trim()

Can you share all the code changes need to be placed?

2024-02-12 06:08 UTC, aksiuwaa commented
src/util/Injected.js in line 270:
`const parsed = window.Store.VCardParse.parseVcard(content);`
`if (parsed) {`
`	vcardOptions = {`
`		type: 'vcard',`
`		vcardFormattedName: parsed.N[0].value.join(' ').trim()`
`	};`
`}`

2024-02-12 17:27 UTC, RemyBoy72 commented
> src/util/Injected.js in line 270: `const parsed = window.Store.VCardParse.parseVcard(content);` `if (parsed) {` ` vcardOptions = {` ` type: 'vcard',` ` vcardFormattedName: parsed.N[0].value.join(' ').trim()` ` };` `}`

thx but it still doesnt work at least for me. any other way to rectify the issue?

2024-02-14 00:08 UTC, raisa875647 commented
**how do I solve this, please explain what needs to be replaced.**

2024-08-12 13:18 UTC, khsoh commented
Can this patch be modified to work on v1.25.0 ?

2024-10-03 14:21 UTC, khsoh commented
Hi, I have tested this patch and it works except when the VCARD contains an EMAIL entry.  For example, in the example.js file, replace the vCard:

```
const vCard =
            'BEGIN:VCARD\n' +
            'VERSION:3.0\n' +
            'FN:John Doe\n' +
            'ORG:Microsoft;\n' +
            'EMAIL;type=INTERNET:john.doe@gmail.com\n' +
            'TEL;type=CELL;type=VOICE;waid=18006427676:+1 (800) 642 7676\n' +
            'END:VCARD';
```

It will not work.  One way to fix this is to replace lines 139-142 of Utils.js with:

```
        vcardOptions = {
            type: 'vcard',
            subtype: null,
            vcardFormattedName: window.Store.VCardUtils.vcardGetNameFromParsed(parsed)
        };

```

2024-10-03 18:03 UTC, alechkos commented
@khsoh Thank you!

2024-11-12 04:20 UTC, Maimbe commented
itit works ? =(

2025-02-14 05:36 UTC, theunisdk commented
Hey All, is there anyway we can help get this update through?

2025-03-29 03:16 UTC, khsoh commented
Hi, the new v1.27.0 branch still has issue with sending VCard.  Here is the fix:

https://github.com/pedroslopez/whatsapp-web.js/compare/v1.27.0...khsoh:feature/vcard-fix-v1.27.0?expand=1

2025-04-07 11:12 UTC, maxkoryukov commented
I merged this PR in a forked version of this repo - and it works

- without #1995 - i receive plain text message of the VCard (in DM, in groups)
- with #1995 - the expected VCard is sent

2025-05-30 13:58 UTC, shirser121 commented on src/util/Injected/Store.js
> +    window.Store.VCardUtils = {
Why don't keep the previous name to keep support?
window.Store.VCard

2025-06-02 11:09 UTC, khsoh commented
Hi @alechkos - can you merge this fix for the next PR:

https://github.com/khsoh/whatsapp-web.js/tree/vcard-fix-v1.30.0-20250602

2025-06-02 18:11 UTC, alechkos commented on src/util/Injected/Store.js
> +    window.Store.VCardUtils = {
Done

2025-06-02 18:17 UTC, alechkos approved these changes
Tested and works as expected.

2025-06-02 19:05 UTC, shirser121 approved these changes
Thanks

2025-06-02 19:08 UTC, merged