feat: added contact_changed event
pedroslopez/whatsapp-web.js pull request #2027
Opened 2023-02-24 21:54 UTC by alechkos

# PR Description
PR adds `contact_changed` event.
The event is emitted when a contact or a group participant changed their phone number (their id will be changed also).

## 1. When a contact changes their phone number:

The notification message that belongs to the event and is shown **in a private chat**:

![2](https://user-images.githubusercontent.com/93551621/220492730-5024ebf0-47a3-40f0-aaee-94c51a0d6ba3.png)

The pop-up message that is shown when clicking on a message:

![3](https://user-images.githubusercontent.com/93551621/220492489-2d199c34-3f4b-47e3-84a0-d10917f814ec.png)

## 2. When a group participant changes their phone number:

The notification messages that belong to the event and are shown **in a group chat**:
1.  In case the contact is in your contact list

![1](https://user-images.githubusercontent.com/93551621/220493611-d2e2a256-25b2-4182-8959-e0dd0bd70e92.png)

2. In case the contact **is not** in your contact list:

![4](https://user-images.githubusercontent.com/93551621/220494031-7d186b10-8f9e-44b0-a960-963b50d8ddf5.png)

## Usage Example (also added to `example.js`)
```javascript
client.on('contact_changed', (notification) => {
    /** The time the event occurred. */
    const eventTime = (new Date(notification.timestamp * 1000)).toLocaleString();

    if (notification.subtype === 'change_number') {
        /**
         * Emitted when a contact changed their phone number.
         * 
         * {@link notification.templateParams} is an array of two user's ids:
         * the old (before the change) and a new one, stored in alphabetical order.
         * 
         * {@link notification.from} is a current user's id that has a Chat with a user,
         * whos phone number was changed.
         * 
         * {@link notification.to} is a user's id (after the change), the current user has a Chat with.
         */

        const newId = notification.to;
        const oldId = notification.templateParams.find(id => id !== newId);

        console.log(`The user ${oldId} changed their phone number at ${eventTime}.\n` +
            `Their new phone number is ${newId.slice(0, -5)}.`)

    }
    else if (notification.subtype === 'modify') {
        /**
         * Emitted when a group participant changed their phone number.
         * 
         * {@link notification.author} is a participant's id before the change.
         * 
         * {@link notification.recipients[0]} is a participant's id after the change,
         * a new one.
         * 
         * {@link notification.to} is a group chat id the event was emitted in.
         * 
         * {@link notification.from} is a current user's id that got an notification message in the group.
         */

        const oldId = notification.author;
        const newId = notification.recipients[0];
        const groupId = notification.to;

        console.log(`The user ${oldId} that participates in group ${groupId} ` +
            `changed their phone number at ${eventTime}.\n` +
            `Their new phone number is ${newId.slice(0, -5)}.`)
    }
});
```

## Related Issue
#1590

## Types of Changes
- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).

2023-03-22 15:03 UTC, tuyuribr requested changes
Please make the ESList god happy

2023-03-22 18:37 UTC, alechkos commented
> Please make the ESList god happy

Thank you
Done

2023-04-01 13:59 UTC, PurpShell approved these changes

2023-04-01 19:16 UTC, tuyuribr approved these changes

2023-04-01 19:30 UTC, merged