Add the 'unread_count' event. Listen to changes on Chat.unreadCount
pedroslopez/whatsapp-web.js pull request #2059
Opened 2023-03-12 00:34 UTC by leftbrasil

# PR Details

Added the listener for the Chat.unreadCount, the event will fire every time the chat unreadCount changes. This is useful on scenarios that we work with cellphone and a custom system.

## Description

-Added the Chat to 'require' section
-Added the required functions to work

Example of use:

```
client.on('unread_count', async (chat) => {
    console.log('Unread count event!');
});

```
## Related Issue

#570 
#1524 

## Motivation and Context

I't solves my problem with tracking read chats between cellphone / whatsapp desktop app and my custom developed application. With this, i know which chats has been read and avoid working on already served customer.

## How Has This Been Tested

Tested using my WhatsApp account (MD)

## Types of changes

- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).

2023-03-14 14:18 UTC, luca-adhocweb commented
Fantastic! It's really what I need. Thanks

2023-03-22 14:48 UTC, tuyuribr requested changes
Please make the ESList god happy

2023-03-22 18:21 UTC, tuyuribr approved these changes

2023-04-01 01:21 UTC, PurpShell approved these changes

2023-04-01 13:59 UTC, merged