Правки
pedroslopez/whatsapp-web.js pull request #2088
Opened 2023-03-21 13:25 UTC by LaboratorySales

# PR Details

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

2023-03-22 14:40 UTC, tuyuribr commented
Cool proxy thing but, please keep this in english. And we already have a discussion here: #1949

2023-04-09 13:25 UTC, PurpShell requested changes
eeeeek keep it all in english and clean your code please. and also no, we won't blindly accept this pull request. @tuyuribr did you read through the code? Did you see what this person is pushing to mainstream exactly?

2023-04-09 13:25 UTC, PurpShell commented on src/Client.js
> +                this.emit('proxy_auth', ip);// ПРОКСИ
very large security risk

2023-04-09 13:30 UTC, PurpShell commented
Seeing that a pull request already exists, no thanks.

2023-04-09 13:30 UTC, closed without merging