Upgade node version
pedroslopez/whatsapp-web.js pull request #2129
Opened 2023-04-09 14:18 UTC by tuyuribr

# PR Details
It's time to upgade the node version

## Description

The latest ubuntu version, installs node v18. So we can upgrade node and the other dependencies 

[https://packages.ubuntu.com/kinetic/nodejs]

## Types of changes

- [x] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## TO DO
- [ ] Quick steps for upgrade
- [ ] Other dependencies update
- [ ] User base test

2023-04-09 14:24 UTC, tuyuribr commented
I think node v16 gives us a little more time to the next upgrade

2023-04-09 14:30 UTC, tuyuribr commented
Which puppeteer version should we choose? What are the breaking changes that we should avoid?
I think we should upgrade to v18.2.1 
https://github.com/puppeteer/puppeteer/tree/v18.2.1

2023-04-09 14:35 UTC, tuyuribr commented
I think we should upgrade node-fetch to v2.6.9 (nice). We are in 2.6.5 so probably won't break a thing.

https://github.com/node-fetch/node-fetch/releases/tag/v2.6.9

2023-04-09 15:20 UTC, amosayomide05 commented
I wonder why the library supports old version

2023-04-09 17:52 UTC, tuyuribr commented
> I wonder why the library supports old version

Because the last version of ubuntu would install node v12 on apt install nodejs

2023-04-10 23:18 UTC, wictornogueira commented
> I think node v16 gives us a little more time to the next upgrade

Sort of... v16 will be reaching EOL in 5 months

2023-04-10 23:38 UTC, wictornogueira commented
Here 👇

### Windows

#### Manual
Just get the latest LTS from https://nodejs.org

#### Choco
```powershell
choco install nodejs-lts
```

#### Winget
```powershell
winget install OpenJS.NodeJS.LTS
```

### Ubuntu / Debian
```bash
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
```

2023-04-10 23:47 UTC, wictornogueira requested changes

2023-04-10 23:47 UTC, wictornogueira commented on README.md
> +--QUICK STEPS TO INSTALL NEW VERSION
Here 👇

### Windows

#### Manual
Just get the latest LTS from https://nodejs.org

#### Choco
```powershell
choco install nodejs-lts
```

#### Winget
```powershell
winget install OpenJS.NodeJS.LTS
```

### Ubuntu / Debian
```bash
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
```

2023-06-05 12:21 UTC, zvictor commented
> > I wonder why the library supports old version
> 
> Because the last version of ubuntu would install node v12 on apt install nodejs

Thanks for sharing this info and for working on this PR! ❤️
I must say, it's quite surprising to learn that the decision to maintain an obsolete version was driven by Ubuntu's default Node.js installation.

Relying on Ubuntu as the primary deployment method seems arbitrary, particularly since this is just one of the many ways one could deploy WWeb applications. Moreover, it appears we haven't documented this decision or provided any deployment guidance, which means only those who happen to be already deploying on Ubuntu would benefit from it.

When I deployed my first app, I turned to Puppeteer's guides for recommended deployment steps. My deployment process still follows one of [their guides](https://pptr.dev/guides/docker).

I wholeheartedly agree with the changes proposed in this PR. As a Node project, rather than an Ubuntu one, it's important that we adhere to Node's release schedule. Sticking to whatever is the `Active LTS` version at the time is standard practice and will help prevent the accumulation of technical debt.

2023-06-12 18:14 UTC, zvictor approved these changes

2023-06-24 04:45 UTC, tuyuribr commented
If you test this PR please include your node version ( `node --version` ), your system OS and the WaWeb version ( `await client.getWWebVersion()` )
Update your package.json to: git+https://github.com/pedroslopez/whatsapp-web.js#tuyuribr-patch-2
Don't forget to delete node_modules them npm i

2023-07-03 19:43 UTC, tofers commented
13 Puppetmaster has stopped working properly.

Some files are not loading.

With Puppeteer 18.2.1 files are loaded successfully.  I will be switching

2023-08-14 03:16 UTC, alechkos approved these changes
Windows 10

Node v18.17.1
Puppeteer v18.2.1
WWeb v2.2333.11
WWebJS v1.22.1

Tested some library functions, version caching and my opened PRs, works perfect

2023-08-23 16:39 UTC, wictornogueira commented
> Warnings: Win7 only supports node 13

Well, we could always add a note about that 🤷
I wouldn't be that concerned, though

2023-08-24 19:25 UTC, diegofemello commented
up

2023-12-17 12:46 UTC, zvictor approved these changes
awesome

2024-04-03 01:04 UTC, PurpShell approved these changes

2024-04-03 01:06 UTC, merged

2024-04-06 14:43 UTC, devagarwal007 commented
how to use this newly pushed code?

2024-04-17 01:43 UTC, washington65145as commented
> how to use this newly pushed code?

do npm install github:pedroslopez/whatsapp-web.js#webpack-exodus in your path project