Improvements in mentionedJidList and content, referring to sendMessage
pedroslopez/whatsapp-web.js pull request #2166
Opened 2023-04-22 12:09 UTC by rafael-ofc

All the changes made do not oblige users to modify their codes, but this adds new options when sending a message, simplifying some tasks.

## mentionedJidList
When mentioning a participant, you don't necessarily need to send an array of objects, but you can also send an array of strings, which makes it easier to mention specific users, see the example below:
```js
const from = msg.from;
const isGroup = from.endsWith("@g.us");
const sender = isGroup ? msg.id.participant : from; //This returns the user id: "5516****8888@c.us"

//Sending messages with mentions
client.sendMessage(from, `Hello @${sender.split('@')[0]}`, {mentions: [sender]})
```

## content
To send files in general, you can provide an object to sendMessage, using two main keys (url or file) and as value you can supply the string directly, this way it will use the MessageMedia static functions internally, inside the function sendMessage, see the example below:
```js
//Sending local files
client.sendMessage(msg.from, {file: "./path/to/image.png"});

//Sending files from a URL
client.sendMessage(msg.from, {url: "https://via.placeholder.com/350x150.png"});
```

## Note
All previous methods can be used normally, without any limitation.

2023-04-22 20:18 UTC, NuevaGeneracionALB commented
Perfeito 👌

2023-04-23 12:58 UTC, shirser121 commented on src/structures/MessageMedia.js
Why add fromAll instead of do the check in the sendMessage and call fromUrl or fromFilePath?

2023-04-23 20:45 UTC, rafael-ofc commented on src/structures/MessageMedia.js
That's an idea too, but when it comes to software architecture, shouldn't each class have its unique responsibilities?

 Anything else I can do is change here.

2023-04-24 03:42 UTC, shirser121 commented on src/structures/MessageMedia.js
@pedroslopez @PurpShell what do you think?

2023-04-24 09:10 UTC, PurpShell commented on src/structures/MessageMedia.js
Greatly disagree with the use of fromAll. This may seem like a good idea, but it'll bring a lot of exploits that allow RCE and file extortion from the filesystem.

2023-04-24 10:21 UTC, rafael-ofc commented on src/structures/MessageMedia.js
> Discordo totalmente do uso de fromAll. Isso pode parecer uma boa ideia, mas trará muitos exploits que permitem RCE e extorsão de arquivos do sistema de arquivos.

Correct, but what about using (fs.existsSync()), do you think it's a good idea to use it?  To know if the path is a url or a folder

2023-04-24 11:17 UTC, rafael-ofc commented on src/structures/MessageMedia.js
![image](https://user-images.githubusercontent.com/108157095/233980599-ad06f0d3-cd97-47c3-9231-42a2221bed9d.png)
I was thinking of using it like this, directly in sendMessage, what do you think?

If it finds the key url, it executes this code, otherwise it continues normally, being able to use other methods.

2023-04-29 10:47 UTC, PurpShell commented on src/structures/MessageMedia.js
Use it in your own code

2023-04-29 10:48 UTC, PurpShell requested changes
Split into more than one pull request

2023-04-29 21:30 UTC, rafael-ofc commented
> Dividido em mais de um pull request

What is to be changed?

2023-04-30 07:22 UTC, NuevaGeneracionALB commented on src/structures/MessageMedia.js
> Use-o em seu próprio código

Difficult the situation of the project, I am thinking of using it for a while and analyzing the response data of the developers of whatsapp-web.js, but do not apply the idea of almost any new developer, and when they launch the idea already ready, they discard the revolution of the project and ask for use in the code itself, and the idea is for the advancement of the project and not itself,  Everything that is created is to maintain stability and also advancement.

2023-05-31 10:27 UTC, PurpShell requested changes
Just revert the fromAll functionality I think. Too many security exploits will be caused by this

2023-05-31 10:27 UTC, PurpShell commented on src/Client.js
> +const fs = require('fs');
```suggestion
```

2023-05-31 10:27 UTC, PurpShell commented on src/Client.js
> +
```suggestion
```

2023-05-31 10:29 UTC, PurpShell approved these changes

2023-05-31 10:32 UTC, Aliyss commented
If we do this it may make sense, that we let the user handle the map serialized and only allow for serialized ids, without the contact object?

@PurpShell

2023-05-31 10:41 UTC, PurpShell commented
> If we do this it may make sense, that we let the user handle the map serialized and only allow for serialized ids, without the contact object?
> 
> @PurpShell

Yes, i think so, to improve code quality and allow for more options and less errors.. Getting the contacts is mostly a hindrance and not an enjoyable time

2023-05-31 10:51 UTC, PurpShell commented
@Aliyss updated

2023-05-31 11:59 UTC, Aliyss approved these changes
lgtm

2023-05-31 12:55 UTC, merged

2023-06-01 17:10 UTC, Aliyss commented
>  If we decided to switch to TS at the time of the TS declarations being added, that would've been much easier to maintain than to have a TS declarations file and an outdated JS config.

 +1 to everything. Lets switch to TS!

2024-01-28 16:36 UTC, loic-hamdi commented
`Mentions with an array of Contact are now deprecated. See more at https://github.com/pedroslopez/whatsapp-web.js/pull/2166.`


`index.d.ts` has not been updated, it still ask for `array of Contact`

```ts
/** Contacts that are being mentioned in the message */
        mentions?: Contact[]
```

2024-02-01 18:58 UTC, amirave commented
bumping @loic-hamdi.