using puppeteer with stealth plugin to avoid detection
pedroslopez/whatsapp-web.js pull request #2190
Opened 2023-05-09 01:14 UTC by maikelohcfg

# PR Details

Introduce using of Stealth Plugin with puppeteer to minimize chances of being detected

## Description

Puppeteer's plugins provide a lot of functionality to improve puppeteer, one of them is the Stealth, here we use it to make harder to detect the automated browser

## Motivation and Context

This change will reduce the risk of detection, which should decrease the number of account banned. This is not a magic solution, sending a lot of messages is still something against WhatsApp policies, so use it wisely

## How Has This Been Tested
Just instantiate the browser, the WhatsApp client as usually. The change is just related to how we launch puppeteer using the proper plugin

## Types of changes
- [x ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x ] I have updated the documentation accordingly (index.d.ts).

2023-05-09 20:41 UTC, tofers commented
Think of the solution as a separate module so you don't depend on it. 

Among those who need it will use

2023-05-10 09:27 UTC, Ermesoml commented
Is that possible to use it as a separated module on the wwebjs?
I'm also interested but I agreed that it could be better as a separated module.

2023-05-31 10:59 UTC, PurpShell commented
Here is what I suggest you do, keep the change you need to make (require puppeteer-extra) and simply require it from your script and add any extensions you need. This way it is not a forced decision.

2023-05-31 10:59 UTC, PurpShell requested changes

2023-05-31 10:59 UTC, PurpShell commented on src/Client.js
> +const StealthPlugin = require('puppeteer-extra-plugin-stealth');
```suggestion
```
add this on your side

2023-05-31 10:59 UTC, PurpShell commented on src/Client.js
> +        puppeteer.use(StealthPlugin());
```suggestion
```
add this on your side as well

2023-06-25 18:34 UTC, closed without merging

2023-11-16 14:13 UTC, kaiser620 commented
I got this error while trying to implement this Puppeteer stealth using this way and making the changes. Error: Navigating frame was detached.