fix: Cannot read properties of undefined (reading '_serialized')
pedroslopez/whatsapp-web.js pull request #2225
Opened 2023-05-22 19:04 UTC by guicuton

# PR Details

Fix undefined `_serialized` param of object `lastReceivedKey` on chat object at *Injected.js* of **WWEBVERSION: 2.2321.6**

## Description

Added ternary condition on `lastReceivedKey` while is trying to get the chat model.
This param are undefined when you don't have any historic of messages with given contact

## Related Issue

Evaluation error while trying to send message for new chats on **WWEBVERSION: 2.2321.6**
![image](https://github.com/pedroslopez/whatsapp-web.js/assets/37594431/105b73b9-4ef1-45d5-9da9-68f9bdd6c3db)

## How Has This Been Tested

- [x] Individual accounts
- [x] Business accounts
- [x] Android
- [ ] IOS

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

2023-05-28 12:19 UTC, zvictor approved these changes

2023-05-28 23:12 UTC, tuyuribr requested changes

2023-05-28 23:12 UTC, tuyuribr commented on README.md
> +[![npm](https://img.shields.io/npm/v/whatsapp-web.js.svg)](https://www.npmjs.com/package/whatsapp-web.js) [![Depfu](https://badges.depfu.com/badges/4a65a0de96ece65fdf39e294e0c8dcba/overview.svg)](htt
revert this

2023-05-28 23:12 UTC, tuyuribr commented on tools/version-checker/.version
> +2.2321.6
revert this

2023-05-29 08:37 UTC, zvictor commented
In my setup, messages are processed externally (lambda) before a serialized `Message` object is sent back. It then has to load the chat object again, often leading to the error described by the OP.

Since i started using the code provided in this PR, the error is gone (My setup is small, just a couple of messages a day).

2023-05-29 13:41 UTC, guicuton commented on README.md
> +[![npm](https://img.shields.io/npm/v/whatsapp-web.js.svg)](https://www.npmjs.com/package/whatsapp-web.js) [![Depfu](https://badges.depfu.com/badges/4a65a0de96ece65fdf39e294e0c8dcba/overview.svg)](htt
Done

2023-05-29 13:41 UTC, guicuton commented on tools/version-checker/.version
> +2.2321.6
Done

2023-06-05 11:24 UTC, zvictor approved these changes

2023-06-15 12:40 UTC, tofers approved these changes

2023-06-22 21:34 UTC, CJRMedeiros123 commented
Work for me!

2023-06-23 06:57 UTC, frreiheit commented
Unfortunately, the problem persists on iOS.

2023-08-03 16:40 UTC, Santosl2 commented
Up .. Merge this please

2023-08-03 16:40 UTC, alechkos approved these changes

2023-08-03 16:41 UTC, Santosl2 approved these changes

2023-08-04 19:27 UTC, tuyuribr approved these changes

2023-08-04 23:30 UTC, aliyss approved these changes

2023-08-07 07:08 UTC, diegofemello commented
Up .. Merge this please²

2023-08-07 15:57 UTC, merged