feat: add new link with phone option
pedroslopez/whatsapp-web.js pull request #2363
Opened 2023-07-27 03:38 UTC by fm1randa

# PR Details

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

2023-07-28 13:43 UTC, shirser121 commented
Thanks you !
If there is anything i can help, please write it down

2023-07-28 21:34 UTC, fm1randa commented
> The things that matter to me are.
> 
> 1. Switching between the two in a running Puppeteer (without restarting the client) by number and back again
> 2. Entering a phone number after starting the client.
> 3. Changing the phone number (in case of its erroneous entry ).
> 4. Whether an error is handled after the codes waiting time expires

1. My approach differs from what you expect. It's not possible to switch between the two. Also, I think it wouldn't be a thing that most users will use. IMO, you usually want to avoid playing around authentication part while automating a Whatsapp session. You want to authenticate and make your automation online as soon as possible. 
2. This library doesn't support user inputs after starting the client.
3. Same answer as the above subject. You can achieve a flexible way to change the phone number (I mean, without changing the source code) by using an environment variable for it.
4. I didn't reproduce this scenario locally. The expiration time is probably too big.

cc @tofers

2023-08-01 13:50 UTC, tofers commented
Required to be reproduced as in the original WA.

1. QR
2. Transition to the phone
3. Switch to QR

These are the basic actions in the original Whatsapp. 

Restarting the puppeteer to switch methods is not the best way.

2023-08-02 17:57 UTC, jgarciach commented
lgtm

how can i help to get this merged?

2023-08-04 19:33 UTC, tuyuribr commented
Good work!

2023-08-05 11:26 UTC, renzhxr commented
haven't been able to get the login code after being linked?

2023-08-05 20:02 UTC, fm1randa commented
> haven't been able to get the login code after being linked?

@renzhxr I'm not sure if I got your issue. Could you describe it better?

If I got your question correctly, the answer is: you won't get any code **after** linking.

2023-08-07 02:00 UTC, andresayac approved these changes
Tested good job

2023-08-08 00:37 UTC, amiruldev20 commented
then how to do client.logout from this method?

2023-08-08 14:54 UTC, fm1randa commented
> then how to do client.logout from this method?

It should work normally 🤔 . Could you test it?

2023-08-09 22:46 UTC, PurpShell requested changes
1. Great work, this retains both options in a reasonable matter and makes it a lot more type secure
2. We had internal discussions before and I also personally found and (almost) made a PR, for getting the QR through internal methods and not the elements. Interacting with the page is not preferred as those can easily break
3. Which gets me to my last point and my only negative one, is there any way to automate the switching, input and code retrieval without interacting with elements at all? If not, I'll still push my auto qr after yours, but I rather we implement new features with a good approach and not randomly.

2023-08-10 20:25 UTC, andresayac approved these changes
I have validated the new changes good job

2023-08-27 22:04 UTC, NavaShield commented
is there a code example on how to log in with a code instead of qr code?

2023-09-07 14:31 UTC, joweste commented
Hi, could you help me to test it?
I just changed manually all your new modified files in my current whatsweb.js node_modules folder.
I have other fixes and I can´t change all folder files with the  yours.

So, I did:
```
import WAWebJS, {
  LinkingMethod,
  Client,
  LocalAuth,
  DefaultOptions
} from "whatsapp-web.js";
....

const client = new Client({
          linkingMethod: new LinkingMethod({
            phone: {
              number: process.env.WWEBJS_TEST_REMOTE_ID.replace("@c.us", "")
            }
          }),
          authStrategy: new LocalAuth({ clientId: `wbot-${whatsapp.id}` }),
          puppeteer: {
            headless: true,
            executablePath: process.env.CHROME_BIN || undefined,
            args: [`--user-agent=${DefaultOptions.userAgent}`, ...minimal_args]
          }
        })

```
After that, when I run my app I get:

```
TypeError: (0 , whatsapp_web_js_1.LinkingMethod) is not a function
    at F:\Programas\vuejs\izing.open.io\backend\src\libs\wbot.ts:232:39
    at processTicksAndRejections (node:internal/process/task_queues:96:5) Unhandled Rejection at Promise Promise {
  <rejected> TypeError: (0 , whatsapp_web_js_1.LinkingMethod) is not a function
      at F:\Programas\vuejs\izing.open.io\backend\src\libs\wbot.ts:232:39
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
}
```

2023-09-28 01:02 UTC, renzhxr commented
please update according to this flow
https://github.com/pedroslopez/whatsapp-web.js/pull/2509

2023-09-28 01:02 UTC, renzhxr commented
please update according to this flow
https://github.com/pedroslopez/whatsapp-web.js/pull/2509

2023-09-30 17:31 UTC, sourabhpatil1992 commented
How to use, not have any example. Please mention in the example.

2023-09-30 21:56 UTC, joweste commented
> How to use, not have any example. Please mention in the example.

I agree. Some PR take long time to merge. Maybe because we can't test because there's a leak of information.

2023-10-20 22:44 UTC, kevindevm commented
i want to test this, how do i do it?

2023-10-23 07:38 UTC, daby186 approved these changes

2023-11-09 18:20 UTC, devsakae commented
> i want to test this, how do i do it?
> Why isn't there a gist with an implementation example?
> How to use, not have any example. Please mention in the example.

https://github.com/pedroslopez/whatsapp-web.js/issues/2587#issuecomment-1800878464

2023-11-10 05:06 UTC, sourabhpatil1992 commented
New version of Client.js is not included this feature. this cause the new update by whatsapp not working on this. And share exampe how can we use this. @fm1randa, @alechkos

2023-11-10 23:06 UTC, diheinsohn commented
Hi, im trying to get a phone code using the following but not getting any event.

`
const client = new Client({
    linkingMethod: new LinkingMethod({
        phone: {
            number: 'xxxxxxxxxxx'
        }
    }),
    authStrategy: new LocalAuth(),
    puppeteer: {
        headless: true
    }
});

client.on('code', code => { console.log(code)});
client.initialize();
`

2023-11-19 22:07 UTC, tdee912 commented
this worked, thank you, although only once the code was generated

2023-11-25 10:13 UTC, MobCode100 commented
I might be in minority here, but as for me, I've encountered an issue of not being able to receive any code. So I've inspected the `Client.js` code and found that the CSS selectors here won't work anymore: 
```
const LINK_WITH_PHONE_BUTTON = '[data-testid="link-device-qrcode-alt-linking-hint"]';
const PHONE_NUMBER_INPUT = '[data-testid="link-device-phone-number-input"]';
const NEXT_BUTTON = '[data-testid="link-device-phone-number-entry-next-button"]';
const CODE_CONTAINER = '[data-testid="link-with-phone-number-code-cells"]';
const GENERATE_NEW_CODE_BUTTON = '[data-testid="popup-controls-ok"]';
const LINK_WITH_PHONE_VIEW = '[data-testid="link-device-phone-number-code-view"]';
```
After fixing the selectors, code can be received but the 'on code' event triggered twice, getting empty code.
![Screenshot from 2023-11-24 11-29-32](https://github.com/pedroslopez/whatsapp-web.js/assets/66469454/ed0d869d-9b9b-42ed-a663-cbf2cea9f15d)

I've made some changes to fix both of that problem on my [fork](https://github.com/MobCode100/whatsapp-web.js/commit/3b77df5f13c25bcf854d5e2666c8e75b01b27251). Anyone can try it with `npm install https://github.com/MobCode100/whatsapp-web.js.git` and the below sample code:
```
const { Client, LinkingMethod, LocalAuth} = require('whatsapp-web.js');
const client = new Client(
    {
        linkingMethod:  new LinkingMethod({
            phone: {
                number: "+<COUNTRY CODE><PHONE NUMBER>"
            }
        }),
        puppeteer: {
            args: ['--no-sandbox'],
        },
    }
);
client.on('code', (code) => {
    console.log('CODE RECEIVED', code);
});
client.on('ready', () => {
    console.log('Client is ready!');
});
client.initialize();
```

Should I make a PR for this? I agree that this approach is more fragile and prone to change. An idea is to expose the underlying JavaScript function that switches the linking method, take a look at ["app.$RANDOM_STRING.js"](https://web.whatsapp.com/app.d5fe617c5b54f888d7bb.js).

![image](https://github.com/pedroslopez/whatsapp-web.js/assets/66469454/836e3679-8e12-4810-9bdf-eec65a3d7fc9)

If somehow we can override the content to expose the `onClickLinkWithPhoneNumber` method and attach to, for example the window object, then we can call that function anytime needed. The challenge is the script is heavily obfuscated so it's a bit more complex than the current approach.

2023-11-27 05:49 UTC, sourabhpatil1992 commented
It Working Fine...

2023-12-05 09:20 UTC, OrdinaryEnder commented
> this worked, thank you, although only once the code was generate ![IMG_20231120_135558](https://private-user-images.githubusercontent.com/9406349/284160363-1a86b3c8-caa8-4ce3-9a02-0cbd0d2953df.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjgyODIsIm5iZiI6MTcwMTc2Nzk4MiwicGF0aCI6Ii85NDA2MzQ5LzI4NDE2MDM2My0xYTg2YjNjOC1jYWE4LTRjZTMtOWEwMi0wY2JkMGQyOTUzZGYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDVUMDkxOTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ0NTUxYTgzZjljN2U1MjAwZDNhMDkyYjFkZjZhZDJkYTYzNzllODQzZDBhMGE2ZjY5NjlmNDM1OGU2N2JmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ma5WbtFx0IwI_H7rFiRVrBqy7iUvzUrak89RUNB3w30)

How did you do it, I tried many times it just doesn't fire anything

2023-12-06 03:01 UTC, MobCode100 commented
> How did you do it, I tried many times it just doesn't fire anything

Can you try my [solution](https://github.com/pedroslopez/whatsapp-web.js/pull/2363#issuecomment-1826272448)? hopefully it'll work. I had the same issue too.

2023-12-08 10:51 UTC, RC047 approved these changes
Works fine !

2023-12-14 05:01 UTC, lord-zeus approved these changes

2023-12-14 18:49 UTC, olmello commented
> then how to do client.logout from this method?

How can I do logout?
not works here

2023-12-14 18:52 UTC, olmello commented
> > then how to do client.logout from this method?
> 
> It should work normally 🤔 . Could you test it?

I tested here.... not works.

2023-12-31 15:49 UTC, PurpShell commented
This PR will not get merged. We are abandoning the HTML element / DOM manipulation elements of WWebJS since they are the easiest to patch by WA.

We are working on pairing code functionality with the new startup flow which will allow us to to get the pairing code through moduleRaid.

2024-01-02 21:45 UTC, lordprana commented
@PurpShell Is there an ETA for when this new pairing code functionality will go live?

2024-01-25 22:56 UTC, pfnh26 commented
the functionality is incredible, I'm designing a chatbot, but I'm very new to code and the library is helping me a lot, I recently created my logic for this functionality but I believe there was some change in WhatsApp web and the functionality stopped, right? I will print the error:
 Error: No node found for selector: div[role="button"] > div > div
    at assert (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at DOMWorld.click (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:287:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleLinkWithPhoneNumber (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\node_modules\whatsapp-web.js\src\Client.js:321:17)
    at async Client.initialize (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\node_modules\whatsapp-web.js\src\Client.js:403:17)
    at async startWhatsAppSession (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\server.js:1363:13)
    at async C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\server.js:935:7
    
    If anyone can solve it, I would be very grateful

2024-01-25 23:44 UTC, Davixe7 commented
> the functionality is incredible, I'm designing a chatbot, but I'm very new to code and the library is helping me a lot, I recently created my logic for this functionality but I believe there was some change in WhatsApp web and the functionality stopped, right? I will print the error: Error: No node found for selector: div[role="button"] > div > div at assert (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15) at DOMWorld.click (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:287:32) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async handleLinkWithPhoneNumber (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\node_modules\whatsapp-web.js\src\Client.js:321:17) at async Client.initialize (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\node_modules\whatsapp-web.js\src\Client.js:403:17) at async startWhatsAppSession (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\server.js:1363:13) at async C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\server.js:935:7
> 
> ```
> If anyone can solve it, I would be very grateful
> ```

As far a i know, there won't be longer support by this feature because it is HTML tag dependant and prone to errors like the one you are facing in this example.

2024-01-25 23:55 UTC, pfnh26 commented
> > a funcionalidade é incrível, estou projetando um chatbot, mas sou muito novo em código e a biblioteca está me ajudando muito, recentemente criei minha lógica para essa funcionalidade mas acredito que houve alguma mudança no WhatsApp web e na funcionalidade parou, certo? Vou imprimir o erro: Error: No node found for selector: div[role="button"] > div > div at assert (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\node_modules\whatsapp-web. js\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15) em DOMWorld.click (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\node_modules\whatsapp-web.js\ node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:287:32) em process.processTicksAndRejections (node:internal/process/task_queues:95:5) em assíncrono handleLinkWithPhoneNumber (C:\Users\Phelipe\Desktop\ Sistema-whatsapp-web2\node_modules\whatsapp-web.js\src\Client.js:321:17) em async Client.initialize (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\node_modules\whatsapp-web .js\src\Client.js:403:17) em startWhatsAppSession assíncrono (C:\Users\Phelipe\Desktop\Sistema-whatsapp-web2\server.js:1363:13) em assíncrono C:\Users\Phelipe\Desktop \Sistema-whatsapp-web2\server.js:935:7
> > ```
> > If anyone can solve it, I would be very grateful
> > ```
> 
> Até onde eu sei, não haverá mais suporte para esse recurso porque ele depende da tag HTML e está sujeito a erros como o que você está enfrentando neste exemplo.

I thought it was because of this: npm i https://github.com/pedroslopez/whatsapp-web.js#main
not working here, by the way there is a command that updates the entire library on your PC, because: npm install whatsapp-web.js It's not working here either

2024-01-26 00:48 UTC, MobCode100 commented
> Anyone can try it with `npm install https://github.com/MobCode100/whatsapp-web.js.git` and the below sample code:
> 
> ```
> const { Client, LinkingMethod, LocalAuth} = require('whatsapp-web.js');
> const client = new Client(
>     {
>         linkingMethod:  new LinkingMethod({
>             phone: {
>                 number: "+<COUNTRY CODE><PHONE NUMBER>"
>             }
>         }),
>         puppeteer: {
>             args: ['--no-sandbox'],
>         },
>     }
> );
> client.on('code', (code) => {
>     console.log('CODE RECEIVED', code);
> });
> client.on('ready', () => {
>     console.log('Client is ready!');
> });
> client.initialize();
> ```

@pfnh26 I've made a temporary modifications in my fork, that fixes the selector for me while waiting for this feature to be completed by this repository. Can I ask you to try and see if it works for you?

2024-01-26 01:56 UTC, pfnh26 commented
> > Qualquer um pode experimentá-lo com `npm install https://github.com/MobCode100/whatsapp-web.js.git`o código de exemplo abaixo:
> > ```
> > const { Client, LinkingMethod, LocalAuth} = require('whatsapp-web.js');
> > const client = new Client(
> >     {
> >         linkingMethod:  new LinkingMethod({
> >             phone: {
> >                 number: "+<COUNTRY CODE><PHONE NUMBER>"
> >             }
> >         }),
> >         puppeteer: {
> >             args: ['--no-sandbox'],
> >         },
> >     }
> > );
> > client.on('code', (code) => {
> >     console.log('CODE RECEIVED', code);
> > });
> > client.on('ready', () => {
> >     console.log('Client is ready!');
> > });
> > client.initialize();
> > ```
> 
> @pfnh26Fiz modificações temporárias em meu fork, que corrigem o seletor para mim enquanto aguardo que esse recurso seja concluído por este repositório. Posso pedir que você experimente e veja se funciona para você?

This change worked, but is it temporary?

Thank you very much, my project really appreciates it

2024-01-26 02:09 UTC, MobCode100 commented
> This change worked, but is it temporary?
> 
> Thank you very much, my project really appreciates it

Happy to have it working for you! It is temporary because WhatsApp Web will make changes on the UI thus, we'll have to update the code again. I'll keep maintaining my fork tho, cause one of my project is using it until whatsapp-web.js have the feature to link by phone.

2024-01-26 02:12 UTC, pfnh26 commented
> > This change worked, but is it temporary?
> > Thank you very much, my project really appreciates it
> 
> Happy to have it working for you! It is temporary because WhatsApp Web can make changes on the UI thus, we'll have to update the code again. I'll keep maintaining my fork tho, cause one of my project is using it until whatsapp-web.js have the feature to link by phone.

Thanks again, but I'm hoping that whatsapp-web.js has this feature natively, we agree that QRcode authentication is very outdated

2024-01-31 11:48 UTC, aidar87 commented
Any updates? will this pull request merged?

2024-04-02 19:49 UTC, pfnh26 commented
> > Essa mudança funcionou, mas é temporária?
> > Muito obrigado, meu projeto realmente agradece
> 
> Fico feliz em tê-lo funcionando para você! É temporário porque o WhatsApp Web pode fazer alterações na UI, portanto teremos que atualizar o código novamente. Vou continuar mantendo meu fork, porque um dos meus projetos está usando-o até que o whatsapp-web.js tenha o recurso de link por telefone.

good afternoon my friend, how are you?
Again we are having the same problem when authenticating using a WhatsApp number, I believe that today WhatsApp made some changes as it also fell due to webVersionCache, but in the end, I would like to know if somehow I can learn to manipulate the code like you do so I can help you update this authentication method, if it's something manual, you can give me the tutorial and I'll make the updates, or if you can do it.
Thank you very much in advance

2024-04-02 20:03 UTC, MobCode100 commented
> > > Essa mudança funcionou, mas é temporária?
> > > Muito obrigado, meu projeto realmente agradece
> > 
> > Fico feliz em tê-lo funcionando para você! É temporário porque o WhatsApp Web pode fazer alterações na UI, portanto teremos que atualizar o código novamente. Vou continuar mantendo meu fork, porque um dos meus projetos está usando-o até que o whatsapp-web.js tenha o recurso de link por telefone.
> 
> good afternoon my friend, how are you?
> Again we are having the same problem when authenticating using a WhatsApp number, I believe that today WhatsApp made some changes as it also fell due to webVersionCache, but in the end, I would like to know if somehow I can learn to manipulate the code like you do so I can help you update this authentication method, if it's something manual, you can give me the tutorial and I'll make the updates, or if you can do it.
> Thank you very much in advance

Thanks for the notice, I'll check the problem and try to fix it later this day. You can modify if you have some knowledge on JavaScript, there a lots of tutorial in the internet. The file to be modified is the `LinkingMethod.js`. Fork my git [repo](https://github.com/MobCode100/whatsapp-web.js). Make your changes, and then install using the command above but be sure to replace the url to your forked git repo. Make sure to change the client headless config to false for testing changes. You can also modify the code directly inside node_modules folder for testing. Goodluck.

2024-04-02 20:08 UTC, pfnh26 commented
> > > > Essa mudança funcionou, mas é temporária?
> > > > Muito obrigado, meu projeto realmente agradece
> > > 
> > > 
> > > Fico feliz em tê-lo funcionando para você! É temporário porque o WhatsApp Web pode fazer alterações na UI, portanto teremos que atualizar o código novamente. Vou continuar mantendo meu fork, porque um dos meus projetos está usando-o até que o whatsapp-web.js tenha o recurso de link por telefone.
> > 
> > 
> > good afternoon my friend, how are you?
> > Again we are having the same problem when authenticating using a WhatsApp number, I believe that today WhatsApp made some changes as it also fell due to webVersionCache, but in the end, I would like to know if somehow I can learn to manipulate the code like you do so I can help you update this authentication method, if it's something manual, you can give me the tutorial and I'll make the updates, or if you can do it.
> > Thank you very much in advance
> 
> Thanks for the notice, I'll check the problem and try to fix it later this day. You can modify if you have some knowledge on JavaScript, there a lots of tutorial in the internet. The file to be modified is the `LinkingMethod.js`. Fork my git [repo](https://github.com/MobCode100/whatsapp-web.js). Make your changes, and then install using the command above but be sure to replace the url to your forked git repo. Make sure to change the client headless config to false for testing changes. You can also modify the code directly inside node_modules folder for testing. Goodluck.

OK, I'll study this, I believe I can help you next time.
I'm looking for an investor so that I can launch this project, in addition to whatsapp-web.js I'm also using other libraries and Python to incorporate an AI model, soon I'll be able to hire people to help with this project, and these errors will no longer be problems ^^

2024-04-03 05:44 UTC, MobCode100 commented
> webVersionCache



> I believe that today WhatsApp made some changes as it also fell due to webVersionCache,

Okay, so I've looked into it. It's an ongoing problem with [WhatsApp Web version 2.3XXX](https://github.com/pedroslopez/whatsapp-web.js/issues/2789). The workaround is to add the `webVersionCache` config as below:

```
const wwebVersion = '2.2412.54';
const client = new Client(
    {
        linkingMethod:  new LinkingMethod({
            phone: {
                number: "+<COUNTRY CODE><PHONE NUMBER>"
            }
        }),
        puppeteer: {
            args: ['--no-sandbox'],
        },
        webVersionCache: {
            type: 'remote',
            remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
        },
    }
);
```
See https://github.com/wppconnect-team/wa-version/tree/main/html for versions.

2024-04-03 10:34 UTC, pfnh26 commented
> > webVersionCache
> 
> > I believe that today WhatsApp made some changes as it also fell due to webVersionCache,
> 
> Okay, so I've looked into it. It's an ongoing problem with [WhatsApp Web version 2.3XXX](https://github.com/pedroslopez/whatsapp-web.js/issues/2789). The workaround is to add the `webVersionCache` config as below:
> 
> ```
> const wwebVersion = '2.2412.54';
> const client = new Client(
>     {
>         linkingMethod:  new LinkingMethod({
>             phone: {
>                 number: "+<COUNTRY CODE><PHONE NUMBER>"
>             }
>         }),
>         puppeteer: {
>             args: ['--no-sandbox'],
>         },
>         webVersionCache: {
>             type: 'remote',
>             remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
>         },
>     }
> );
> ```
> 
> Be sure to update your whatsapp-web.js package with `npm update`. See https://github.com/wppconnect-team/wa-version/tree/main/html for versions.

Sorry for not telling you how to resolve the webVersionCache error, below is the solution:
• In src/util/constants.js to replace:
webVersionCache: {
type: 'remote',
remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2410.1.html',
}

It's the same thing you did, but including it this way you don't need to write it inside the client code.

2024-04-03 10:42 UTC, MobCode100 commented
> It's the same thing you did, but including it this way you don't need to write it inside the client code.

Thank you for this, I'll make this change soon!

2024-04-03 10:47 UTC, pfnh26 commented
> 
> ```
> const wwebVersion = '2.2412.54';
> const client = new Client(
>     {
>         linkingMethod:  new LinkingMethod({
>             phone: {
>                 number: "+<COUNTRY CODE><PHONE NUMBER>"
>             }
>         }),
>         puppeteer: {
>             args: ['--no-sandbox'],
>         },
>         webVersionCache: {
>             type: 'remote',
>             remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
>         },
>     }
> );
> ```

Did you manage to resolve the "LinkingMethod" error?
Is it already operational?
I'm using it this way:
const { Client, LinkingMethod, LocalAuth} = require('whatsapp-web.js');
const client = new Client(
    {
        linkingMethod:  new LinkingMethod({
            phone: {
                number: "+000000000"
            }
        }),
        puppeteer: {
            args: ['--no-sandbox'],
        },
    }
);
client.on('code', (code) => {
    console.log('CODE RECEIVED', code);
});
client.on('ready', () => {
    console.log('Client is ready!');
});
client.initialize();

2024-04-03 11:25 UTC, MobCode100 commented
> Is it already operational?

Yes, you can use it normally now. Just run `npm update`.

2024-04-03 12:43 UTC, pfnh26 commented
> > Is it already operational?
> 
> Yes, you can use it normally now. Just run `npm update`.
The code is not being generated, could I be doing something wrong?

2024-04-03 14:47 UTC, MobCode100 commented
> The code is not being generated, could I be doing something wrong?

Try to delete your session folder, or maybe reinstall my repo:
```
npm uninstall whatsapp-web.js
npm install https://github.com/MobCode100/whatsapp-web.js.git
```

2024-04-03 15:46 UTC, pfnh26 commented
> > The code is not being generated, could I be doing something wrong?
> 
> Try to delete your session folder, or maybe reinstall my repo:
> 
> ```
> npm uninstall whatsapp-web.js
> npm install https://github.com/MobCode100/whatsapp-web.js.git
> ```

I did this, but the code is not generated, it does not give an error, but it also does not generate the code.
Is it the format of the WhatsApp number?
` const { Client, LinkingMethod, LocalAuth} = require('whatsapp-web.js');
const client = new Client(
    {
        linkingMethod:  new LinkingMethod({
            phone: {
                number: "+000000000000"
            }
        }),
        puppeteer: {
            args: ['--no-sandbox'],
        },
    }
);
client.on('code', (code) => {
    console.log('CODE RECEIVED', code);
});
client.on('ready', () => {
    console.log('Client is ready!');
});
client.initialize();`

2024-04-03 19:25 UTC, MobCode100 commented
> Is it the format of the WhatsApp number?

I don't think so, I've tried exactly your code and I'm able to receive the code from WhatsApp. Maybe try new number? Just in case, I've changed the WhatsApp version in my repo. You can try to reinstall again.

2024-04-06 00:33 UTC, pfnh26 commented
> > Is it the format of the WhatsApp number?
> 
> I don't think so, I've tried exactly your code and I'm able to receive the code from WhatsApp. Maybe try new number? Just in case, I've changed the WhatsApp version in my repo. You can try to reinstall again.

Sorry for the delay in testing, but it still doesn't work for me, the format I used before was like this <+556292286543>
my country changed the number by adding the number 9 after 62, like this
<+5562992286543> but this change was not necessary the first time the code worked, please if you can check why it is not working, when I request the code event it simply does not happen, nor does it give an error in my code

2024-04-06 18:43 UTC, MobCode100 commented
> <+5562992286543> but this change was not necessary the first time the code worked, please if you can check why it is not working,

I've tried that number, I still can get the code... very strange. Let's not spam our conversations here, create an issue [here](https://github.com/MobCode100/whatsapp-web.js/issues).

2024-04-08 11:42 UTC, pfnh26 commented
> > <+5562992286543> but this change was not necessary the first time the code worked, please if you can check why it is not working,
> 
> I've tried that number, I still can get the code... very strange. Let's not spam our conversations here, create an issue [here](https://github.com/MobCode100/whatsapp-web.js/issues).

here it is :
https://github.com/MobCode100/whatsapp-web.js/issues/1

2024-04-14 01:59 UTC, closed without merging

2024-04-14 01:59 UTC, PurpShell commented
#2816

2024-05-17 17:10 UTC, pfnh26 commented
@MobCode100 all good?
Today the error was reported:
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Unable to read properties from undefined (reading 'push')
    in fillModuleArray (evaluation in <anonymous> (:2:5), <anonymous>:6:74)

Updating this way I managed to solve:
npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

You can update yours:
npm install https://github.com/MobCode100/whatsapp-web.js.git

please?

2024-05-17 17:25 UTC, MobCode100 commented
Does webpack exodus supports phone linking method?

2024-05-17 17:29 UTC, pfnh26 commented
> Does webpack exodus supports phone linking method?



> Does webpack exodus supports phone linking method?

unfortunately not

2024-05-18 20:46 UTC, pfnh26 commented
@MobCode100 
I made a small modification to the client instantiation by adding:
webVersionCache: {
        type: "remote",
        remotePath: "https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2412.54.html"
    }

2024-06-30 15:46 UTC, jaygent commented
will this pull request merged?

2024-07-02 06:21 UTC, yairmelamed commented
ready dsnt fire..

2024-07-02 11:32 UTC, MobCode100 commented
This feature is already in webpack-exodus. However it's currently in testing phase. 

To use it just `npm install github:pedroslopez/whatsapp-web.js#webpack-exodus`

Sample app code:
```
const { Client, LocalAuth } = require('whatsapp-web.js');

// Phone number format: "COUNTRY_CODE""PHONE_NUMBER"
const wsacc_phone_number = "601154035979";

const client = new Client(
    {
        puppeteer: {
            args: ['--no-sandbox'],
            headless: false
        },
        authStrategy: new LocalAuth({ dataPath: "." })
    }
);

// Pairing code only needs to be requested once
let pairingCodeRequested = false;
client.on('qr', async () => {
    if(!pairingCodeRequested){
        const code = await client.requestPairingCode(wsacc_phone_number,true);
        console.log('WS LOGIN CODE:', code);
        pairingCodeRequested = true;
    }
});

client.initialize();
```

2024-07-02 11:52 UTC, yairmelamed commented
Thanks [MobCode100](https://github.com/MobCode100).. I tried it but it didn't work for me..

2024-07-02 14:05 UTC, yairmelamed commented
Thanks [MobCode100](https://github.com/MobCode100).. It works!!

2025-05-25 18:53 UTC, MobCode100 commented
> Hello @MobCode100 your fork doesnt work anymore I think. The pairing method doesnt work :/ Since today or few days I think

Thanks for mentioning... I'll check this later this day... Can you show me any errors?

2025-07-18 09:08 UTC, nihatsen commented
> This feature is already in webpack-exodus. However it's currently in testing phase.
> 
> To use it just `npm install github:pedroslopez/whatsapp-web.js#webpack-exodus`
> 
> Sample app code:
> 
> ```
> const { Client, LocalAuth } = require('whatsapp-web.js');
> 
> // Phone number format: "COUNTRY_CODE""PHONE_NUMBER"
> const wsacc_phone_number = "PUT YOUR PHONE NUMBER";
> 
> const client = new Client(
>     {
>         puppeteer: {
>             args: ['--no-sandbox'],
>             headless: false
>         },
>         authStrategy: new LocalAuth({ dataPath: "." })
>     }
> );
> 
> // Pairing code only needs to be requested once
> let pairingCodeRequested = false;
> client.on('qr', async () => {
>     if(!pairingCodeRequested){
>         const code = await client.requestPairingCode(wsacc_phone_number,true);
>         console.log('WS LOGIN CODE:', code);
>         pairingCodeRequested = true;
>     }
> });
> 
> client.initialize();
> ```

how to handle code renewal apart from qr renewal ? When the code refreshes, how will we know

2025-07-18 09:45 UTC, MobCode100 commented
> how to handle code renewal apart from qr renewal ? When the code refreshes, how will we know

See #3180, unfortunately you have to handle it manually for now

2025-10-09 14:12 UTC, azampasha0033 commented
I am Getting teh following Error 
can anyone help ?
Requesting pairing code for phone number: 9230******
Error while requesting pairing code: Error: Evaluation failed: b
    at ExecutionContext._ExecutionContext_evaluate (/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async Client.requestPairingCode (/node_modules/whatsapp-web.js/src/Client.js:368:16)
    at async Client.<anonymous> (file:///clients/getClient.js:252:22)

2025-10-10 06:44 UTC, azampasha0033 commented
Hi Any one can help please i am using the following code to link the phone number but i git the error as 
❌ Pairing flow error: Evaluation failed: b
and logs are 

📱 Waiting before requesting pairing code for 92303****19 ...
📱 Initiating pairing flow for 92303***** ...
❌ Pairing flow error: Evaluation failed: b

  if (mode === 'phone' && phone && !pairingCodeRequested) {
    pairingCodeRequested = true;
    console.log(`📱 Waiting before requesting pairing code for ${phone} ...`);

    // ✅ Wait for WhatsApp DOM to load (prevents window.onCodeReceivedEvent error)
setTimeout(async () => {
  try {
    console.log(`📱 Initiating pairing flow for ${phone} ...`);
    const code = await client.requestPairingCode(phone, true);
    console.log(`🔑 Pairing code for ${phone}:`, code);

    global.io?.to(clientId).emit('pairing-code', { clientId, code, phone });
    sessionStatus.set(clientId, 'pairing');
  } catch (err) {
    console.error('❌ Pairing flow error:', err.message);
  }
}, 6000);

    return; // ⛔ stop here, don’t generate QR
  }
  
  
  
  and i am using teh following remote Auth
  const wwebVersion = '2.2417.1';

const client = new Client({
  authStrategy: new RemoteAuth({
    store,
    clientId,
    backupSyncIntervalMs: 300000, // 5 mins
  }),
  puppeteer: {
    headless: true,
    args:
      process.env.NODE_ENV === 'production'
        ? [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-gpu',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--disable-web-security',
            '--disable-features=IsolateOrigins,site-per-process',
            '--disable-features=VizDisplayCompositor',
            '--single-process',
            '--no-zygote',
            '--renderer-process-limit=1',
            '--no-first-run',
            '--no-default-browser-check',
            '--disable-background-networking',
            '--disable-background-timer-throttling',
            '--disable-backgrounding-occluded-windows',
            '--disable-breakpad',
            '--disable-client-side-phishing-detection',
            '--disable-component-update',
            '--disable-default-apps',
            '--disable-domain-reliability',
            '--disable-extensions',
            '--disable-hang-monitor',
            '--disable-ipc-flooding-protection',
            '--disable-notifications',
            '--disable-offer-store-unmasked-wallet-cards',
            '--disable-popup-blocking',
            '--disable-prompt-on-repost',
            '--disable-renderer-backgrounding',
            '--disable-sync',
            '--force-color-profile=srgb',
            '--metrics-recording-only',
            '--mute-audio',
            '--no-crash-upload',
            '--no-pings',
            '--password-store=basic',
            '--use-gl=swiftshader',
            '--use-mock-keychain',
            '--disable-software-rasterizer',
          ]
        : [],
  },
 webVersionCache: {
  type: 'remote',
  remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
},
});