feat: added group settings + fix: `GroupChat` methods
pedroslopez/whatsapp-web.js pull request #2444
Opened 2023-08-26 14:21 UTC by alechkos

# PR Details

### - [Description](#description)

### - [Usage Example](#usage-example)

### - [How Has the PR Been Tested (latest test on 26.08.2023)](#tests)
- [**The environment the PR was tested on**](#env)
- [**I want to test this PR**](#pr-testing)
- [**I have an issue while testing this PR**](#pr-testing-issue)

### - [Types of Changes](#types-of-changes)

---

## Description <a href="#description" id="description"/>
1. Group settings added:
    - `setMembershipApprovalMode` - sets the [Membership Approval Mode](https://faq.whatsapp.com/1110600769849613), when turned on, group admins must approve anyone who wants to join the group
    - `setReportToAdminMode`- sets the [Report To Admin Mode](https://faq.whatsapp.com/919039336073667), when turned on, every group participant could report every message sent in the group, these reports will be sent to group admins for review. Group admin could see those reports in *Sent for admin review* section in the group
    - `setMessageExpiration` - sets [message expiration timer](https://faq.whatsapp.com/673193694148537) for the chat. Valid values for passing to the method are:
        - **0** for message expiration removal
        - **1** for 24 hours message expiration
        - **2** for 7 days message expiration
        - **3** for 90 days message expiration
2. `groupMetadata` extended with properties:
    - `iAmMember` - indicates if a current user is a member in the group
    - `iAmAdmin` - indicates if a current user is an admin in the group
    - `iAmSuperAdmin` - indicates if a current user is an admin who created the group
3. `leave` method fixed - now the method returns boolean value: true if the operation completed successfully, false otherwise
4. Other minor fixes

## Usage Example (also added to example.js) <a href="#usage-example" id="usage-example"/>
```js
client.on('message', async (msg) => {
    if (msg.body === '!msgTimer') {
        const chat = await client.getChatById('groupId@g.us'/** or number@c.us */);
        /**
         * Valid values for passing to the method are:
         * 0 for message expiration removal,
         * 1 for 24 hours message expiration,
         * 2 for 7 days message expiration,
         * 3 for 90 days message expiration
         */
        /** For 24 hours message expiration: */
        await chat.setMessageExpiration(1);
    } else if (msg.body === '!reportToAdminMode') {
        const group = await client.getChatById('groupId@g.us');
        if (group.isGroup) {
            /** Turns the 'Report To Admin Mode' on: */
            await group.setReportToAdminMode(true);
            /** Turns the 'Report To Admin Mode' off: */
            await group.setReportToAdminMode(false);
        }
    } else if (msg.body === '!membershipApprovalMode') {
        const group = await client.getChatById('groupId@g.us');
        if (group.isGroup) {
            /** Turns the 'Membership Approval Mode' on: */
            await group.setMembershipApprovalMode(true);
            /**
             * Turns the 'Membership Approval Mode' off
             * Note: if the mode is turned off, all pending requests to join the group will be approved
             */
            await group.setMembershipApprovalMode(false);
        }
    }
});
```

## How Has This Been Tested <a href="#tests" id="tests"/>
Was tested with a code provided in usage example.

### Tested On (latest test on 26.08.2023): <a href="#env" id="env"/>

#### Types of accounts:
- Personal
- Buisness

#### Environment:
- Android 10
- Windows 10:
    - WWebJS **v1.22.1**
    - WWeb **v2.2333.11**
    - Puppeteer **v18.2.1**
    - Node **v18.17.1**
    - Chrome **v116.0.5845.111**

### To test this PR by yourself you can run one of the following commands: <a href="#pr-testing" id="pr-testing"/>

- **NPM**
```powershell
npm install github:alechkos/whatsapp-web.js#chat-group-props
```
- **YARN**
```powershell
yarn add github:alechkos/whatsapp-web.js#chat-group-props
```
<details><summary>

### If you encounter any issues while testing this PR, please provide in a comment (click to expand): <a href="#pr-testing-issue" id="pr-testing-issue"/>
</summary>

1. The code you've used without any sensitive information (use [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) for more readability)
5. The library version
6. The WWeb version: `console.log(await client.getWwebVersion());`
7. The browser (Chrome/Chromium)
8. The error you got
</details>

## Types of Changes <a href="#types-of-changes" id="types-of-changes"/>
- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).

2023-08-28 00:31 UTC, tuyuribr commented
Good work, just a note `group_join` triggering when someone need admin approve to join is a breaking change.
Someone might be using this to tag users in a welcome message and it will fail for this scenario.
Anyway, This scenario should trigger `group_join`, I don't think we need a new event just for approval, What do you think?

2023-08-28 02:38 UTC, alechkos commented
@tuyuribr 
Made `group_join` event docs clarifications

2023-12-22 17:22 UTC, matheus-de-araujo approved these changes
Very document code, congratulations

2024-05-10 13:12 UTC, Halphas commented
Did this also fix set group description and set group profile pic? If not, I can provide it if u like.

2024-10-31 04:23 UTC, rizwan1239 commented
It stays stuck at "Authenticated Successfully" and no event seems to be fired. Any idea?

2024-10-31 04:27 UTC, rizwan1239 commented
After installing this PR, it stays stuck at "Authenticated Successfully" and no event seems to be fired. Any idea?

2025-09-24 08:27 UTC, purpshell requested changes
Mandatory block

2025-09-27 14:36 UTC, closed without merging