Update Client.js
pedroslopez/whatsapp-web.js pull request #2482
Opened 2023-09-07 10:58 UTC by Gautam--Roy

Fixes #2473, #2479

# PR Details

Added multiple selectors from the logged-in page

## Description

The current and alpha versions refer to [data-icon="chat"] css selector when waiting for authenticated/logged-in page load. WhatsApp has since changed the selector to "new-chat" instead of "chat". This PR adds multiple selectors with wildcard substring selection for the css selectors that are present on the logged-in page.

## Related Issue

## Motivation and Context

This will solve the "ready event not firing" issue after QR Code scan.
Should fix : 
https://github.com/pedroslopez/whatsapp-web.js/issues/2479
https://github.com/pedroslopez/whatsapp-web.js/issues/2473

## How Has This Been Tested

Tested locally and private remote server.
Env :
NodeJS v18.15.0
whatsapp-web.js 1.22.2-alpha.0

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

2023-09-07 12:42 UTC, sourabhpatil1992 commented
TimeoutError: waiting for function failed: timeout 30000ms exceeded
at Promise.race.page.waitForSelector.timeout (/home/sourabh/youngMind/node_modules/whatsapp-web.js/src/Client.js:181:22)
    at new Promise (<anonymous>)
    at Client.initialize (/home/sourabh/youngMind/node_modules/whatsapp-web.js/src/Client.js:180:13)

2023-09-07 12:43 UTC, sourabhpatil1992 requested changes
at Promise.race.page.waitForSelector.timeout (/home/sourabh/youngMind/node_modules/whatsapp-web.js/src/Client.js:181:22)
    at new Promise (<anonymous>)
    at Client.initialize (/home/sourabh/youngMind/node_modules/whatsapp-web.js/src/Client.js:180:13)

2023-09-08 01:40 UTC, Gautam--Roy commented
@sourabhpatil1992 : Timeout added. Should be good now. Also, please mention your environment so it's easier to debug. Best regards

2023-09-08 05:19 UTC, Ndohjapan approved these changes

2023-09-08 05:31 UTC, sourabhpatil1992 approved these changes
approve change

2023-09-13 16:33 UTC, AlloryDante approved these changes

2023-09-14 13:57 UTC, tuyuribr commented
Dupe of #2474

2023-09-14 13:57 UTC, closed without merging