feat: Community
pedroslopez/whatsapp-web.js pull request #2531
Opened 2023-09-23 02:46 UTC by alechkos

<br/> <br/>
<h1 align="center">WIP</h1>

2023-09-24 23:30 UTC, Epale10 approved these changes

2023-12-03 13:45 UTC, alechkos commented
@crash-overdrive 
> Also, will this PR support mentioning and tagging subgroups from other subgroups in the community?

I did not add that feature here but there is an open [PR](https://github.com/pedroslopez/whatsapp-web.js/pull/2602) that implements group mentions

2023-12-03 15:52 UTC, crash-overdrive commented
> @crash-overdrive
> 
> > Also, will this PR support mentioning and tagging subgroups from other subgroups in the community?
> 
> I did not add that feature here but there is an open [PR](https://github.com/pedroslopez/whatsapp-web.js/pull/2602) that implements group mentions

Thank you, I will help test the group mention PR and will let you know if I find any issues! Thanks for the great work!

2024-01-30 19:23 UTC, joweste commented
How could I change the community description of a created one?

2024-01-30 19:35 UTC, alechkos commented
@joweste 
> How could I change the community description of a created one?

As mentioned in description, the `Community` class extends the `GroupChat` class, so all itls methods are also accessible in the `Community` class.
You can use the [`GroupChat.setDescription`](https://docs.wwebjs.dev/GroupChat.html#setDescription) method:

```js
// client initialization...

const community = await client.getChatById('XXXXXXXXXX@g.us');
await community.setDescription('new description');
```

2024-02-01 01:46 UTC, joweste commented
Hi, I am testing again.
I am member of a third community with 10 groups. I am member in 3 groups.
If I use:  console.log(await community.getJoinedSubgroups());
It returns  3 groups
but  console.log(await community.getUnjoinedSubgroups()) return a empty array

2024-02-01 01:52 UTC, alechkos commented
@joweste 
> [but if I use `console.log(await community.getUnjoinedSubgroups()) ` it returns a empty array]
(https://github.com/pedroslopez/whatsapp-web.js/pull/2531#issuecomment-1920339641)

I think maybe the `getUnjoinedSubgroups` returns an array of community subgroups that you have been a member of in the past and then unjoined them, what do you think?

2024-02-01 01:56 UTC, alechkos commented
@joweste 
> [Hi, I am testing the community feat. All is working well, until I test the getParticipants(). It returns null.](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#issuecomment-1919355090)

I'll check it later, what wweb version do you use? The pr was tested on wweb v2.2347.56 and the latest stable one for now is v2.2405.0

2024-02-01 11:19 UTC, joweste commented
> @joweste
> 
> > [but if I use `console.log(await community.getUnjoinedSubgroups()) ` it returns a empty array](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#issuecomment-1920339641)
> 
> I think maybe the `getUnjoinedSubgroups` returns an array of community subgroups that you have been a member of in the past and then unjoined them, what do you think?

My wweb is 2.2405.1 and,

Yes, You are  sure. I did a test. I just get out of a group and It appears as unjoined. 

But I have a problem. As you see in attached image, I have some community groups where my mobile says I can enter, such as:
Mautic, Quepasa  and Whaticket groups.

But this groups doesn´t appears in any results of the community methods you have created.

![image](https://github.com/pedroslopez/whatsapp-web.js/assets/30800736/54b1fda1-5576-4fc3-8a28-91c6ca4fcab0)

2024-02-01 14:58 UTC, joweste commented
How to query the 
status of membershipApprovalMode and allowNonAdminSubGroupCreation of a community by id?

2024-02-01 19:03 UTC, alechkos commented
@joweste 
> [But I have a problem. As you see in attached image, I have some community groups where my mobile says I can enter
> But those groups don´t appear in any results of the community methods you have created.](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#issuecomment-1921091780)

If you are not a member of a community, you won't see it in results

2024-02-01 19:32 UTC, joweste commented
> @joweste
> 
> > [But I have a problem. As you see in attached image, I have some community groups where my mobile says I can enter
> > But those groups don´t appear in any results of the community methods you have created.](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#issuecomment-1921091780)
> 
> If you are not a member of a community, you won't see it in results

But I am member in 3 groups in that community.

2024-02-01 19:33 UTC, alechkos commented
@joweste 
> But I am member in 3 groups in that community.

But you are not a member of the community itself

2024-02-01 19:41 UTC, joweste commented
> @joweste
> 
> > But I am member in 3 groups in that community.
> 
> But you are not a member of the community itself

Ok, I am going to ask add me as community member.

About the getParticipants problem?  Is it the same problem, because I am not a community member?

2024-02-01 19:43 UTC, joweste commented
> @joweste
> 
> > [How to query the ProfilePicUrl, membershipApprovalMode and allowNonAdminSubGroupCreation of a community by id?](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#issuecomment-1921527386)
> 
> What do you mean _"to query"_? Go through the [description](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#description)

Never mind. These values settings are in groupMetadata.

2024-02-01 19:43 UTC, alechkos commented
@joweste 
> About the getParticipants problem? Is it the same problem, because I am not a community member?

In order to get community members you have at least to be its member, got through [this](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#usage-example-a8)

2024-02-01 19:54 UTC, joweste commented
> @joweste
> 
> > [About the getParticipants problem? Is it the same problem, because I am not a community member?](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#issuecomment-1922099087)
> 
> In order to get community members you have at least to be its member, as mentioned [here](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#usage-example-a8)

Sorry, but the community admin just said me, if I am member at least one group of the community, then I am already member of the community. Does it make sense?

2024-02-01 20:01 UTC, joweste commented
> @joweste
> 
> > Sorry, but the community admin just said me, if I am member at least one group of the community, then I am already member of the community.
> 
> You are right, my fault. I have to check the [`Community.getParticipants`](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#usage-example-a8) method, could be that sonething is broke in the latest wweb versions

Thank you. Could you see why I can´t list all groups in the community where I am member as well?

2024-02-03 00:28 UTC, joweste commented
Only as information, if I get the my commonGroups  with the community admin user, it shows 10 groups.
For sample:
if 'nn' is the serialized id of the admin communnity user, and I do:
```
const contact = await client.getContactById(nn);
const commomGroups = await contact.getCommonGroups();

```
It reports all 10 groups of the community.

But if get the subgroups of the community as:

```
const community = await client.getChatById('XXXXXXXXXX@g.us');
console.log(await community.getSubgroups());

```
 it reports only 4 groups

2024-02-03 14:32 UTC, joweste commented
Hi, when I get  the subgroups participants of a community, I get many @lid numbers.

For sample:
```
const groupChat = await client.getChatById(subgroup community id);
const participants = await groupChat.groupMetadata.participants;
```
Here, 'participants' has many @lid numbers.

What does it means? It seems it´s not  contains the correct id of contact.

2024-02-03 18:27 UTC, joweste commented
Please, What's difference between join a group and link a group to community?

2024-02-03 18:51 UTC, joweste commented
>>With joinSubgroup  you as a user can become a member of one of the community subgroups (similar to acceptInvite)

Hi, But in your sample, you are joining a group to community, not a user.  Is this ok?
```
const community = await client.getChatById('XXXXXXXXXX@g.us');
result = await community.joinSubgroup('YYYYYYYYY@g.us');
```

2024-02-03 19:03 UTC, joweste commented
> @joweste
> 
> > Hi, But in your sample, you are joining a group to community, not a user. Is this ok?
> 
> In the sample I am not joining a group to community, but the current user (a bot) joins the subgroup of a community

I got it. Thanks.
This syntax is more clear to me:
```
/** Joins a community subgroup by community ID and a subgroup ID */
 joinSubgroup: (communityId: string, subGroupId: string) => Promise<JoinGroupResponse>;

```

2024-02-04 21:47 UTC, joweste commented
Hi, does  a specific subgroup can be linked to many communities?

2024-02-12 16:19 UTC, saumilsdk commented
Really required feature!! Please approve and merge :)

2024-02-24 23:28 UTC, joweste commented
> @joweste
> 
> > Sorry, but the community admin just said me, if I am member at least one group of the community, then I am already member of the community.
> 
> You are right, my fault. I have to check the [`Community.getParticipants`](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#usage-example-a8) method, could be that sonething is broke in the latest wweb versions

Hi, is there some news about it? Sorry to ask you.

2024-03-24 17:20 UTC, reddyram commented
Does group_join and group_ leave with communities as well?
I mean do they get triggered when user leaves or joins a community?

2025-01-03 01:33 UTC, RDKclick commented
If you join a community and the administrator sets the case that you cannot view group members, can you export group members' mobile phone numbers? All I got was group member lid

2025-02-06 08:08 UTC, wushiji1995 commented
When I use the createCommunity api, I get the error below: 
**Error: window.Store.CommunityUtils is undefined**

WWebVersion = 2.3000.1019885728
Chromium version = 107.0.5296.0
WWebJS = 1.26.1-alpha.2

2025-04-01 14:25 UTC, Aldione commented
> When I use the createCommunity api, I get the error below: **Error: window.Store.CommunityUtils is undefined**
> 
> WWebVersion = 2.3000.1019885728 Chromium version = 107.0.5296.0 WWebJS = 1.26.1-alpha.2

same issue

2025-04-02 08:53 UTC, Aldione commented
/home/aldione/whatsapp_api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'getDefaultSubgroup')
    at window.WWebJS.getChatModel (pptr://puppeteer_evaluation_script:462:87)
    at async window.WWebJS.getChat (pptr://puppeteer_evaluation_script:489:16)
    at async pptr://puppeteer_evaluation_script:2:20
    at ExecutionContext._ExecutionContext_evaluate (/home/aldione/whatsapp_api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/home/aldione/whatsapp_api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async Client.getChatById (/home/aldione/whatsapp_api/node_modules/whatsapp-web.js/src/Client.js:987:20)
    at async Client.<anonymous> (/home/aldione/whatsapp_api/test.js:29:20)

Node.js v18.19.0

2025-09-10 11:11 UTC, RC047 commented
is there any update for this?

2025-09-10 11:14 UTC, alechkos commented
No and won't be in a near future.

2025-09-10 11:25 UTC, alechkos commented
> [is there any update for this?](https://github.com/pedroslopez/whatsapp-web.js/pull/2531#issuecomment-3274477290)

No and won't be in the nearest future.

2025-09-24 08:27 UTC, purpshell requested changes
Mandatory block

2025-09-27 14:36 UTC, closed without merging

2026-05-21 11:03 UTC, luiscuriel commented
Why was this closed? did it not work? not stable? thanks