fix: Message.getInfo()
pedroslopez/whatsapp-web.js pull request #2574
Opened 2023-10-10 13:55 UTC by alechkos

# Table of Contents <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2574#toc" id="toc"/>

### - [Description](https://github.com/pedroslopez/whatsapp-web.js/pull/2574#description)

### - [Related Issue](https://github.com/pedroslopez/whatsapp-web.js/pull/2574#related-issues)

### - [I Want to Test this PR](https://github.com/pedroslopez/whatsapp-web.js/pull/2574#pr-testing)

### - [How Has the PR Been Tested (latest test on 10.10.2023)](https://github.com/pedroslopez/whatsapp-web.js/pull/2574#tests)
- [**The environment the PR was tested on**](https://github.com/pedroslopez/whatsapp-web.js/pull/2574#env)
- [**I have an issue while testing this PR**](https://github.com/pedroslopez/whatsapp-web.js/pull/2574#pr-testing-issue)

### - [Types of Changes](https://github.com/pedroslopez/whatsapp-web.js/pull/2574#types-of-changes)

---

## Description <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2574#description" id="description"/>
In latest versions wa renamed some module which caused an issue, the PR fixes that issue.

## Related Issue <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2574#related-issues" id="related-issues"/>
PR fixes #2567

## To test this PR by yourself you can run one of the following commands: <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2574#pr-testing" id="pr-testing"/>

- **NPM**
```powershell
npm install github:alechkos/whatsapp-web.js#fix-getInfo
```
- **YARN**
```powershell
yarn add github:alechkos/whatsapp-web.js#fix-getInfo
```

## How Has This Been Tested (latest test on 10.10.2023) [_[Back to TOC]_](https://github.com/pedroslopez/whatsapp-web.js/pull/2574#toc) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2574#tests" id="tests"/>
Was tested with a code below:
```js
client.on('message_create', async (message) => {
    console.log(await (await client.sendMessage(message.to, 'TEST')).getInfo());
});
```

The response after the message was read by one participant:
```js
{
  delivery: [],
  deliveryRemaining: 1,
  played: [],
  playedRemaining: 2,
  read: [
    {
      id: [
        {
          server: 'c.us',
          user: 'XXXXXXXXXX',
          _serialized: 'XXXXXXXXXX@c.us'
        }
      ],
      t: 169XXXXXXX
    }
  ],
  readRemaining: 1
}
```

### Tested On: <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2574#env" id="env"/>

#### Types of accounts:
- Personal
- Buisness

#### Environment:
- Android 10
- Windows 10:
    - WWebJS **1.22.2-alpha.1**
    - WWeb **v2.2333.11**, **v2.2343.55**
    - Puppeteer **v18.2.1**
    - Node **v18.17.1**
    - Chrome **v117.0.5938.150**

<details><summary>

### If you encounter any issues while testing this PR, please provide in a comment (click to expand): <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2574#pr-testing-issue" id="pr-testing-issue"/>
</summary>

1. The code you've used without any sensitive information (use [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) for more readability)
2. The library version
3. The WWeb version: `console.log(await client.getWWebVersion());`
4. The browser (Chrome/Chromium)
5. The error you got

> [!IMPORTANT]
> **You have to [reapply](https://github.com/pedroslopez/whatsapp-web.js/pull/2574#pr-testing) the PR each time it is changed (new commits were pushed since your last application)**
</details>

## Types of Changes [_[Back to TOC]_](https://github.com/pedroslopez/whatsapp-web.js/pull/2574#toc) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2574#types-of-changes" id="types-of-changes"/>
- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix/feature that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project
- [ ] I have updated the usage example accordingly (example.js)
- [ ] I have updated the documentation accordingly (index.d.ts)

2023-10-16 20:17 UTC, CSFelix approved these changes
Tested it locally and worked!!

2023-10-17 04:57 UTC, N0N4M3BNS commented
If using web version 2.2344.53 not work. Can check it?

2023-10-20 14:27 UTC, N0N4M3BNS approved these changes

2023-10-20 14:28 UTC, N0N4M3BNS approved these changes
Ok working now.

2023-10-21 16:16 UTC, tuyuribr requested changes

2023-10-21 16:16 UTC, tuyuribr commented on src/structures/Message.js
> +            if (!msg?.fromMe) return null;
This will break node 13

2023-10-21 16:22 UTC, tuyuribr approved these changes
Good work

2023-10-27 18:53 UTC, wilsinho8 commented
Im testing and i got this error: 

![image](https://github.com/pedroslopez/whatsapp-web.js/assets/49174750/da945161-b73a-4e5d-b01a-8768d8513c1e)

2023-10-27 19:00 UTC, alechkos commented
@wilsinho8 
> Im testing and i got this error

It's very easy to READ the PR description
Written specially for you lol:
https://github.com/pedroslopez/whatsapp-web.js/pull/2574#pr-testing-issue

2023-11-24 10:18 UTC, shirser121 approved these changes
Thanks!

2023-11-24 10:18 UTC, merged