fix: `Client.acceptInvite`
pedroslopez/whatsapp-web.js pull request #2642
Opened 2023-11-21 08:15 UTC by alechkos

> [!IMPORTANT]
> https://github.com/pedroslopez/whatsapp-web.js/labels/Breaking%20change

# Table of Contents

### - [Description](https://github.com/pedroslopez/whatsapp-web.js/pull/2642#description)

### - [Related Issue](https://github.com/pedroslopez/whatsapp-web.js/pull/2642#related-issues)

### - [Usage Example](https://github.com/pedroslopez/whatsapp-web.js/pull/2642#usage-example)

### - [I Want to Test this PR](https://github.com/pedroslopez/whatsapp-web.js/pull/2642#pr-testing)

### - [I Got an Error While Testing This PR ❌](https://github.com/pedroslopez/whatsapp-web.js/pull/2642#pr-testing-issue)

### - [How Has the PR Been Tested](https://github.com/pedroslopez/whatsapp-web.js/pull/2642#tests) (latest test on 21.11.2023)
- [**The environment the PR was tested on**](https://github.com/pedroslopez/whatsapp-web.js/pull/2642#env)

### - [Types of Changes](https://github.com/pedroslopez/whatsapp-web.js/pull/2642#types-of-changes)

---

## Description <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2642#description" id="description"/>
The `Client.acceptInvite` method previously encountered an error when attempting to accept an invitation link for a group with [Membership Approval Mode](https://faq.whatsapp.com/1110600769849613) turned on.
The PR fixes that issue, and also improves user convenience by merging `Client.acceptGroupV4Invite` into `Client.acceptInvite`, now you can achieve the same result using a single method.
Furthermore, the `Client.acceptInvite` method's return value now provides additional information, including error codes and their explanations, to help better understand any issues that may occur during the method's execution.
For not to break a lot the `Client.acceptGroupV4Invite` method hasn't been removed, all the underlying logic has been migrated to the `Client.acceptInvite`.

---

## Related Issue <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2642#related-issues" id="related-issues"/>
The PR closes #2570

---

## Usage Example <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2642#usage-example" id="usage-example"/>

```js
client.on('message', async (msg) => {
    if (msg.body.startsWith('!join ')) {
        const inviteCode = msg.body.split(' ')[1];
        const result = await client.acceptInvite(inviteCode);
        /**
         * Example of the {@link result} object:
         * 
         * {
         *   gid: {
         *     server: 'g.us',
         *     user: '26422642XX',
         *     _serialized: '26422642XX@g.us'
         *   },
         *   code: 200,
         *   message: 'You joined the group/community successfully'
         * }
         */
        console.log(result);
    } else if (msg.body === '!joinViaInviteV4' && msg.hasQuotedMsg) {
        const quotedMsg = await msg.getQuotedMessage();
        if (quotedMsg.inviteV4) {
            await client.acceptInvite(quotedMsg.inviteV4);
        }
    }
});
```

---

## To test this PR by yourself you can run one of the following commands: <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2642#pr-testing" id="pr-testing"/>

- **NPM**
```powershell
npm install github:alechkos/whatsapp-web.js#fix-accept-invite
```
- **YARN**
```powershell
yarn add github:alechkos/whatsapp-web.js#fix-accept-invite
```

---

## If you encounter any errors while testing this PR, please provide in a comment: <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2642#pr-testing-issue" id="pr-testing-issue"/>

1. The code you've used without any sensitive information (use [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) for more readability)
2. The error you got
3. The library version
4. The WWeb version: `console.log(await client.getWWebVersion());`
5. The browser (Chrome/Chromium)

> [!IMPORTANT]
> **You have to [reapply](https://github.com/pedroslopez/whatsapp-web.js/pull/2642#pr-testing) the PR each time it is changed (new commits were pushed since your last application)**

---

## How Has The PR Been Tested (latest test on 21.11.2023) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2642#tests" id="tests"/>

### Tested On: <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2642#env" id="env"/>

#### Types of accounts:
- Personal
- Buisness

#### Environment:
- Android 10
- Windows 10:
    - WWebJS **1.23.1-alpha.0**
    - WWeb **v2.2350.52**
    - Puppeteer **v18.2.1**
    - Node **v18.17.1**
    - Chrome **v119.0.6045.160**

---

## Types of Changes <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/2642#types-of-changes" id="types-of-changes"/>
- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project
- [X] I have updated the usage example accordingly (example.js)
- [X] I have updated the documentation accordingly (index.d.ts)

2024-01-14 07:52 UTC, shirser121 commented
If the result object used to return `{status: number}` we should keep the status property, maybe instead of the code property

2024-01-14 21:49 UTC, alechkos commented
@shirser121 
> [If the result object used to return `{status: number}` we should keep the `status` property, maybe instead of the `code` property](https://github.com/pedroslopez/whatsapp-web.js/pull/2642#issuecomment-1890875813)

I changed to `statusCode` to be more conventional, since the [`createGroup`](https://github.com/pedroslopez/whatsapp-web.js/blob/1c26913c3a6958958aa33a4e0b0704ec82e806cd/src/Client.js#L1364) method of a `Client` class also returns `statusCode` in it

2024-01-15 05:30 UTC, shirser121 commented
> @shirser121
> 
> > [If the result object used to return `{status: number}` we should keep the `status` property, maybe instead of the `code` property](https://github.com/pedroslopez/whatsapp-web.js/pull/2642#issuecomment-1890875813)
> 
> I changed to `statusCode` to be more conventional, since the [`createGroup`](https://github.com/pedroslopez/whatsapp-web.js/blob/1c26913c3a6958958aa33a4e0b0704ec82e806cd/src/Client.js#L1364) method of a `Client` class also returns `statusCode` in it

It's still will break the current behavior

2024-01-15 05:33 UTC, shirser121 commented
So let keep it less breaking...
If you can keep the property, we should.
Add all the other properties, but keep to old one.
This is my opinion anyway

2024-05-23 21:18 UTC, 918483 commented
@alechkos Is there any way to join groups without invitations if I have the group ID on hand?

2025-09-24 08:28 UTC, purpshell requested changes
Mandatory block

2025-09-27 14:36 UTC, closed without merging