Fix window.Store.ProfilePic.profilePicFind is not a function error
pedroslopez/whatsapp-web.js pull request #3001
Opened 2024-05-02 13:02 UTC by seowzhenjun0126

# PR Details

Replace `window.Store.ProfilePic.profilePicFind` with `window.Store.ProfilePic.requestProfilePicFromServer`

## Description

The function

`window.Store.ProfilePic.profilePicFind`

is no longer available in v2.3x, and is replaced with

`window.Store.ProfilePic.requestProfilePicFromServer`

![image](https://github.com/pedroslopez/whatsapp-web.js/assets/56989187/403096e1-2ea8-4f6c-b75e-780f1da2d3ae)

## Related Issue

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

2024-05-02 19:59 UTC, StiflerPasha commented
and how about previous wa-versions?

2024-05-02 20:03 UTC, alechkos commented
@StiflerPasha 
> and how about previous wa-versions?

In 2.2412.54, `window.Store.ProfilePic.profilePicFind` is defined

2024-05-03 09:09 UTC, StiflerPasha commented
We need to make an implementation that is supported on both versions

2024-05-03 17:11 UTC, alechkos requested changes
@seowzhenjun0126 

Add support for previous WWeb versions,
you can use `window.WWebJS.compareWwebVersions` that is located in
`src/util/Injected/Utils.js`

2024-05-06 17:16 UTC, guigo613 requested changes
In this case, it will break for older versions. I believe the best solution would be something like:

```javascript
return await (window.Store.ProfilePic.profilePicFind || window.Store.ProfilePic.requestProfilePicFromServer)(chatWid);
```

2024-05-07 07:20 UTC, N0N4M3BNS approved these changes

2024-05-08 13:12 UTC, mauriciopfl commented
> In this case, it will break for older versions. I believe the best solution would be something like:
> 
> ```js
> return await (window.Store.ProfilePic.profilePicFind || window.Store.ProfilePic.requestProfilePicFromServer)(chatWid);
> ```

Don`t work
Error on: window.WWebJS.compareWwebVersions

2024-05-14 21:08 UTC, alechkos commented on src/Client.js
> +                return await (window.WWebJS.compareWwebVersions(window.Debug.VERSION, '<', '2.3000.0') ? window.Store.ProfilePic.profilePicFind(chatWid) : window.Store.ProfilePic.requestProfilePicFro
```suggestion
                return window.WWebJS.compareWwebVersions(window.Debug.VERSION, '<', '2.3000.0')
                    ? await window.Store.ProfilePic.profilePicFind(chatWid)
                    : await window.Store.ProfilePic.requestProfilePicFromServer(chatWid);
```

2024-05-14 21:10 UTC, merged

2024-05-15 16:53 UTC, Lyfhael commented
Hey,
Should it be modified from this file too maybe ? https://github.com/pedroslopez/whatsapp-web.js/blob/41b280c769918db03ac6ec12cf0e4215e7b864ef/docs/Client.js.html#L1227

2024-07-26 11:19 UTC, erm3nda commented
This has stopped to work for me few days ago, I don't know the exact moment. 
requestProfilePicFromServer function still exists but throws internal error evaluating e.isNewsletter and breaks.