fix: Updated params structure in createGroup function
pedroslopez/whatsapp-web.js pull request #3157
Opened 2024-07-01 05:46 UTC by rbkayz

# PR Details

In a recent update of WA Web,  the params structure of createGroup was modified to an object. As a result, the createGroup function was failing.

this patch fixes that

## Description

```
createGroupResult = await window.Store.GroupUtils.createGroup(
                    title,
                    participantWids,
                    messageTimer,
                    parentGroupWid
                );
```

was modified to

```
createGroupResult = await window.Store.GroupUtils.createGroup(
                    {title, parentGroupId, messageTimer},
                    participantWids,
                );
```

## Related Issue

No issue raised so far

## Motivation and Context

## How Has This Been Tested

Tested in my local environment
- WA version: 2.3000.x
- OS: Windows
- Browser: Chrome

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

2024-07-01 05:48 UTC, rbkayz commented
@alechkos - Please take a look. Thank you!

2024-07-01 06:33 UTC, alechkos requested changes
I checked whatsapp internal method `createGroup`, you implementation has some errors
The method have to take these params:

```js
createGroup(
    {
        announce: true
        ephemeralDuration: 0
        full: undefined
        memberAddMode: true
        membershipApprovalMode: false
        parentGroupId: undefined
        restrict: true
        thumb: undefined
        title: "Test"
    },
    [ /* user wids here*/ ]
);
```

Additionally our entire `createGroup` method have to be reviewed and reimplemented

2024-07-02 16:18 UTC, tuyuribr commented
You were close, but we need to force like this:
window.Store.GroupUtils.createGroup({title:'title',messageTimer:0,parentGroupId:undefined},[pWid]).
I will test and commit directly to the farewellbranch, thanks bro!

2024-07-02 16:25 UTC, closed without merging

2024-07-02 16:25 UTC, rbkayz commented
Thank you @tuyuribr - I see you've just added this commit. I'm going to close this PR.

2024-07-03 09:17 UTC, rbkayz commented
Hey @tuyuribr - can I suggest one change. Can we make `announce` and `restrict` to false. Or atleast just announce for default. Ideally, the new group that's created should not be such that only admins can send messages

2024-07-03 11:42 UTC, rbkayz commented
Updated the types here - https://github.com/pedroslopez/whatsapp-web.js/pull/3179