Mentions
pedroslopez/whatsapp-web.js pull request #35
Opened 2020-02-05 18:46 UTC by Aliyss

I added it like this, but honestly it isn't really optimal. The first set returns id's only. The function converts the ids to Contacts and returns it as an array of Contacts. Do you see a more likeable solution?

2020-02-05 22:09 UTC, Aliyss commented
On the other hand I could make it it's own object. As a collection of Contacts?

2020-02-05 22:50 UTC, pedroslopez requested changes
This looks fine to me! Just a couple comments.

2020-02-05 22:50 UTC, pedroslopez commented on src/structures/Message.js
> +         * @type {[id]}
```suggestion
         * @type {Array<string>}
```

2020-02-05 22:50 UTC, pedroslopez commented on src/structures/Message.js
> +     * @returns {[Promise<Contact>]}
```suggestion
     * @returns {Promise<Array<Contact>>}
```

2020-02-05 22:50 UTC, pedroslopez commented on src/structures/Message.js
> +        this.mentions = [];
Rename `mentions` to `mentionedIds` to indicate the difference between this and the other function.

2020-02-05 22:57 UTC, pedroslopez commented on src/structures/Message.js
> +        for (let i = 0; i < this.mentions.length; i++) {
I would prefer using `map` over loops like these. Makes it clearer.

2020-02-05 23:21 UTC, Aliyss commented
Okok will push the changes in the morning.

2020-02-06 19:47 UTC, merged

2020-02-07 10:20 UTC, Aliyss commented
Doesn't give an error if own user is mentioned, but doesn't return clean data.