feat: Wpp Business's Labels support
pedroslopez/whatsapp-web.js pull request #378
Opened 2020-10-13 22:41 UTC by dyegoaurelio

We're now able to work with Wpp Business's Labels

I added methods to get all labels, get all labels a chat is marked and to fetch all chats a Label is marking

2020-10-25 22:59 UTC, pedroslopez requested changes
Thanks for contributing! Sorry it took a while to review.

Looks good overall and works functionality-wise. However, I believe instead of returning regular objects for labels in functions like `client.getChatLabels()` and `client.getLabels()`, we should opt for creating a Class that represents a ChatLabel. This way, we have a structured representation of labels and their properties that can be properly documented. It could also be useful if we want to add functions like editing labels in the future.

2020-10-25 22:59 UTC, pedroslopez commented on src/Client.js
> +        return JSON.parse( await this.pupPage.evaluate(async () => {
No need to encode/decode JSON here. Puppeteer takes care of serializing the models.
Also, no need to `return await`. Opt for `return` instead. The https://eslint.org/docs/rules/no-return-await rule will be enabled on eslint soon.

2020-10-25 22:59 UTC, pedroslopez commented on src/Client.js
> +        return JSON.parse( await this.pupPage.evaluate(async (chatId) => {
Same as before, JSON conversion and no `return await`.

2020-10-25 22:59 UTC, pedroslopez commented on src/Client.js
> +        return ( await this.pupPage.evaluate(async (labelId) => {
Unneeded `return await`

2020-10-25 22:59 UTC, pedroslopez commented on src/structures/Chat.js
> +        return await this.client.getChatLabels(this.id._serialized);
Unneeded `return await`

2020-10-25 22:59 UTC, pedroslopez commented on src/util/Injected.js
> +        return window.Store.Label.models.map( function (label){  return  { 'name': label.name , 'hexColor': label.hexColor , 'id':label.id }; });
Prefer arrow functions here to keep consistent with the rest of the code.

2020-10-25 22:59 UTC, pedroslopez commented on src/util/Injected.js
> +        //console.log(chatLabelsIndex)
Remove commented code

2020-10-25 22:59 UTC, pedroslopez commented on src/util/Injected.js
> +            res.push({ 'name': window.Store.Label.get(chatLabelsIndex[i]).name , 'hexColor': window.Store.Label.get(chatLabelsIndex[i]).hexColor ,  'id' : chatLabelsIndex[i] } );
I'm seeing in multiple places you're constructing this object representation of a Label with the same properties. To keep things consistent and remove code duplication, perhaps we could instead have a serializer function, much like we have with `getChatModel` and `getMessageModel` that takes care of returning a properly serialized representation of the label with the necessary properties.

2020-10-31 19:22 UTC, closed without merging

2020-10-31 19:38 UTC, dyegoaurelio commented
Closed this pr accidentally
reopened at #407