add getLastSeen method to Chat
pedroslopez/whatsapp-web.js pull request #553
Opened 2021-02-17 20:55 UTC by wictornogueira

2021-03-01 04:11 UTC, pedroslopez commented
I was initially trying to implement this back here https://github.com/pedroslopez/whatsapp-web.js/commit/ddfb616d1bb41f52aa194f71150f10a000050095 but I haven't had time to finish it. Thanks for working on this!

The issue I encountered back then was that getting the presence information could be out of date or not accurate when retrieving it if you're not subscribed to their updates. This can be seen with people that are far down in the chat list.

Unfortunately the function used to subscribe to presence updates doesn't update the presence right away, so I was experimenting with how to accurately retrieve the state after subscribing. One could argue a `setTimeout` could be used with a fixed value, but I'd like to avoid this and use something more reliable. Would appreciate if you could look into this!

2021-07-23 17:43 UTC, Invy55 commented
> I was initially trying to implement this back here [ddfb616](https://github.com/pedroslopez/whatsapp-web.js/commit/ddfb616d1bb41f52aa194f71150f10a000050095) but I haven't had time to finish it. Thanks for working on this!
> 
> The issue I encountered back then was that getting the presence information could be out of date or not accurate when retrieving it if you're not subscribed to their updates. This can be seen with people that are far down in the chat list.
> 
> Unfortunately the function used to subscribe to presence updates doesn't update the presence right away, so I was experimenting with how to accurately retrieve the state after subscribing. One could argue a `setTimeout` could be used with a fixed value, but I'd like to avoid this and use something more reliable. Would appreciate if you could look into this!
> 
> Also, I think having this method on the `Contact` would make more sense.

I was looking into this and I'm having trouble with data disappearing on a normal Firefox instance with manual code execution, any suggestion? I think it has to be something with focusing or the window not being used for some time. (I know this isn't strictly related but I'm hoping in some help)

2022-08-14 15:32 UTC, tuyuribr requested changes
`  chat.presence.subscribe()` needs to be reliable

2022-08-14 15:34 UTC, wictornogueira commented
Mfw yuri necroposts lol

2023-08-07 16:42 UTC, shirser121 commented
Is this still relevant?

2025-02-27 20:30 UTC, purpshell approved these changes
fix conflicts and merge

2025-02-27 23:22 UTC, closed without merging