feat(dev): add new event page loaded
pedroslopez/whatsapp-web.js pull request #709
Opened 2021-06-21 15:23 UTC by ricardoapaes

Adding a new event when the page is loaded and you can interact with the DOM using the puppeter, below is a practical example:

> Adding a new div to the html for example:
> - Request login to your internal system before starting whatsapp.

2021-06-22 18:12 UTC, PurpShell commented
hey! i wouldn't get how this is effective? Does this allow editing of the UI? Maybe something we can accomplish differently. 

Thank you for your contributions. 

Best regards, 

[PurpShell](https://github.com/PurpShell)

2021-06-26 11:42 UTC, JoseHM8A commented
wow, i think this solved my problem getting the profile pictures of participants/groups.

Thank so much

2021-07-05 16:43 UTC, ricardoapaes commented
> hey! i wouldn't get how this is effective? Does this allow editing of the UI? Maybe something we can accomplish differently.
> 
> Thank you for your contributions.
> 
> Best regards,
> 
> [PurpShell](https://github.com/PurpShell)

@PurpShell 

Since I'm using the puppeteer in "headless: false" mode and I'm integrating with my web software, I'd like before opening whatsapp itself the user would login to my software so that I can get session information to be used later, so I add other html tags that contain the login form.

I couldn't find an easier way to do this since the events provided by the platform are only emitted after whatsapp is loaded.

If you have a better suggestion for my problem I am open to other opinions.

2021-08-04 17:43 UTC, PurpShell commented
> > hey! i wouldn't get how this is effective? Does this allow editing of the UI? Maybe something we can accomplish differently.
> > Thank you for your contributions.
> > Best regards,
> > [PurpShell](https://github.com/PurpShell)
> 
> @PurpShell
> 
> Since I'm using the puppeteer in "headless: false" mode and I'm integrating with my web software, I'd like before opening whatsapp itself the user would login to my software so that I can get session information to be used later, so I add other html tags that contain the login form.
> 
> I couldn't find an easier way to do this since the events provided by the platform are only emitted after whatsapp is loaded.
> 
> If you have a better suggestion for my problem I am open to other opinions.

looks good.

2021-09-06 21:47 UTC, PurpShell commented
unstale

2021-12-10 19:28 UTC, PurpShell requested changes
just a slight change

2021-12-10 19:28 UTC, PurpShell commented on src/Client.js
> +        this.emit(Events.PAGE_LOADED, page);
```suggestion
        await page.waitForSelector('[class=web]');
        this.emit(Events.PAGE_LOADED, page);
```

2022-06-23 07:09 UTC, closed without merging