Add buttons && List
pedroslopez/whatsapp-web.js pull request #756
Opened 2021-07-14 14:11 UTC by tuyuribr

Draft to add list and buttons.
Thanks to @PurpShell

2021-07-14 15:36 UTC, PurpShell commented
all in for that credit lol

good job

2021-07-14 18:25 UTC, creuza commented
how can i use this new feature?

2021-07-14 19:13 UTC, PurpShell commented
> how can i use this new feature?

it is a draft.

2021-07-14 20:49 UTC, tuyuribr commented
Button example:
```javascript

//text button
let button = new Buttons("body",[{body:"bt1"},{body:"bt2"},{body:"bt3"}],"title","footer");
client.sendMessage(message['from'], button);


//media button ( Testing, images works fine )

let media = MessageMedia.fromFilePath("image.png");
let button = new Buttons(media,[{body:"bt1"},{body:"bt2"},{body:"bt3"}],"title","footer");
client.sendMessage(message['from'], button,{'caption':"body"});

```

2021-07-14 20:55 UTC, tuyuribr commented
Button tests needed :
Android Business
IOS Standart and Business

2021-07-14 21:02 UTC, creuza commented
`(node:6580) UnhandledPromiseRejectionWarning: ReferenceError: Buttons is not defined`

I received this, even updating the project

2021-07-14 21:12 UTC, PurpShell commented
> `(node:6580) UnhandledPromiseRejectionWarning: ReferenceError: Buttons is not defined`
> 
> I received this, even updating the project

have you cloned the PR????? are you using NPM?

2021-07-14 21:16 UTC, creuza commented
i use npm

2021-07-14 21:27 UTC, creuza commented
now it worked!

`const { Client,  Buttons } = require('whatsapp-web.js');`

it was missing to declare the Buttons
![Uploading WhatsApp Image 2021-07-14 at 18.25.45.jpeg…]()

2021-07-15 18:14 UTC, tuyuribr commented
List example:

```javascript
let sections = [{title:'sectionTitle',rows:[{id:'customId', title:'ListItem1', description: 'desc'},{title:'ListItem2'}]}];
let list = new List('aaa','btnText',sections,'Title','footer');
client.sendMessage(message['from'], list);
```
Lists aren't working on business right now

Tests needed:
Ios Standard

2021-07-22 23:00 UTC, esteves67 commented
> Button example:
> 
> ```js
> //text button
> let button = new Buttons("body",[{body:"bt1"},{body:"bt2"},{body:"bt3"}],"title","footer");
> client.sendMessage(message['from'], button);
> 
> 
> //media button ( Testing, images works fine )
> 
> let media = MessageMedia.fromFilePath("image.png");
> let button = new Buttons(media,[{body:"bt1"},{body:"bt2"},{body:"bt3"}],"title","footer");
> client.sendMessage(message['from'], button,{'caption':"body"});
> ```
> 
> Button tests needed :
> Android Business
> IOS Standard and Business

Tested on Android Business, and iOS Standard, and its working.
Idk about iOS Business.

2021-07-23 04:30 UTC, esteves67 commented
I've been testing this PR, but faced into a problem, i know this PR isn't ready yet, but just wanted you guys to know.

When you have a conversation with buttons, if you use client.getChats you get a problem with map (https://github.com/pedroslopez/whatsapp-web.js/issues/297)

2021-07-23 07:16 UTC, esteves67 commented
I've been testing this DRAFT, and took notes of some things.

Number 1:
When you have a conversation with buttons (using this PR), if you use client.getChats you get a problem with map (https://github.com/pedroslopez/whatsapp-web.js/issues/297)
The only solution for now its to delete the whole conversation that has buttons in it, and the map function works again.
If you guys can test it, test it out, just to make sure its not my fault in my client.getChats function.

Number 2:
Buttons are not getting logged on the console, only the main message gets logged to the console, i guess its not being recognized by whatsapp-web.js yet.

2021-07-23 18:44 UTC, PurpShell commented
> I've been testing this DRAFT, and took notes of some things.
> 
> Number 1:
> When you have a conversation with buttons (using this PR), if you use client.getChats you get a problem with map (#297)
> The only solution for now its to delete the whole conversation that has buttons in it, and the map function works again.
> If you guys can test it, test it out, just to make sure its not my fault in my client.getChats function.
> 
> Number 2:
> Buttons are not getting logged on the console, only the main message gets logged to the console, i guess its not being recognized by whatsapp-web.js yet.

Makes more sense since buttons_message is way different than templateMessage which msg.buttons is trying to act with

2021-07-23 21:46 UTC, tuyuribr commented
> 
> 
> I've been testing this DRAFT, and took notes of some things.
> 
> Number 1:
> When you have a conversation with buttons (using this PR), if you use client.getChats you get a problem with map (#297)
> The only solution for now its to delete the whole conversation that has buttons in it, and the map function works again.
> If you guys can test it, test it out, just to make sure its not my fault in my client.getChats function.
> 
> Number 2:
> Buttons are not getting logged on the console, only the main message gets logged to the console, i guess its not being recognized by whatsapp-web.js yet.

Thanks for your help!

2021-07-25 10:08 UTC, esteves67 commented
> I've been testing this DRAFT, and took notes of some things.
> 
> Number 1:
> When you have a conversation with buttons (using this PR), if you use client.getChats you get a problem with map (#297)
> The only solution for now its to delete the whole conversation that has buttons in it, and the map function works again.
> If you guys can test it, test it out, just to make sure its not my fault in my client.getChats function.
> 
> Number 2:
> Buttons are not getting logged on the console, only the main message gets logged to the console, i guess its not being recognized by whatsapp-web.js yet.

Ignore number 1, as it is already solved by https://github.com/pedroslopez/whatsapp-web.js/issues/386

2021-08-03 16:16 UTC, iamshouvikmitra commented
Any idea when we can have this shipped?
Super excited!

2021-08-03 17:23 UTC, PurpShell requested changes

2021-08-03 17:23 UTC, PurpShell commented on src/structures/Buttons.js
> +            // throw '[BT02] MessageMedia not ready';
kill this.

2021-08-03 18:47 UTC, PurpShell approved these changes
LGTM!

2021-08-04 12:42 UTC, 0xT01 commented
send list/buttons error
```
(node:979379) UnhandledPromiseRejectionWarning: TypeError: Util.generateHash is not a function
at rows.section.rows.map (whatsapp-web.js/src/structures/List.js:68:55)
```

how to fix.?

2021-08-04 21:42 UTC, PurpShell commented
> send list/buttons error
> 
> ```
> (node:979379) UnhandledPromiseRejectionWarning: TypeError: Util.generateHash is not a function
> at rows.section.rows.map (whatsapp-web.js/src/structures/List.js:68:55)
> ```
> 
> how to fix.?

the util functions have disappeared on your end? This is not an issue, since Util is required on the top of the file.

2021-08-05 12:15 UTC, ricocrivelli commented
How can I help to test this functionality?

2021-08-07 00:39 UTC, 0xT01 commented
Hey guys.
I've tried send message list and button,
for a smooth list to be sent.
I tried to send a button message but it didn't send even there was no error message from the system, it looks normal but the message is not sent, I use personal whatsapp.

responses:
```
Message {
  mediaKey: undefined,
  id:
   { fromMe: true,
     remote:
      { server: 'c.us',
        user: '62xxxx',
        _serialized: '62xxxx@c.us' },
     id: '3EB0CB3BE1BB703750DD',
     _serialized: 'true_628xxxx@c.us_3EB0CB3BE1BB703750DD' },
  ack: 0,
  hasMedia: false,
  body: 'ini test body button',
  type: 'chat',
  timestamp: 1628296215,
  from: '62xxxx@c.us',
  to: '62xxxx@c.us',
  author: undefined,
  deviceType: 'web',
  isForwarded: false,
  forwardingScore: 0,
  isStatus: undefined,
  isStarred: false,
  broadcast: undefined,
  fromMe: true,
  hasQuotedMsg: false,
  location: undefined,
  vCards: [],
  inviteV4: undefined,
  mentionedIds: [],
  orderId: undefined,
  token: undefined,
  title: 'ini test title',
  links: undefined,
  dynamicReplyButtons:
   [ { buttonId: 'ySE9Te', buttonText: [Object], type: 1 },
     { buttonId: 'VkcgC7', buttonText: [Object], type: 1 },
     { buttonId: 'JiwHP8', buttonText: [Object], type: 1 } ] }
```
please give directions so that the message button can be sent. thank you

2021-08-07 13:40 UTC, tonvital commented
@0xT01 
i think only whatsapp business can send buttons and lists.

2021-08-07 14:20 UTC, 0xT01 commented
@tonvital 
I've tried using WhatsApp for business. and the result list message is not sent. only personal whatsapp can and the list message is sent. this is a button message that has not got a solution

2021-08-07 14:23 UTC, 0xT01 commented
![Screenshot_2021-08-07-21-21-27-07_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/87315860/128603371-2e24efa5-9c8d-40bd-b32d-e266234d2f65.jpg)
![Screenshot_2021-08-07-21-21-30-95_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/87315860/128603387-35edb7d5-b508-4921-aca4-7cfe72432a74.jpg)

2021-08-07 16:03 UTC, tuyuribr commented
> 
> 
> @0xT01
> i think only whatsapp business can send buttons and lists.

Nope, WaBiz can't send lists because something is off.
I'm sending buttons rn from a standard account

![image](https://user-images.githubusercontent.com/45042245/128606322-bf600af6-2a96-4f3a-8bf0-058e3753f21b.png)

2021-08-08 02:53 UTC, 0xT01 commented
@tuyuribr

yes. but the button doesn't work on the standard account I have.

[0xT01 ](https://github.com/pedroslopez/whatsapp-web.js/pull/756#issuecomment-894578698l)

> Hey guys.
> I've tried send message list and button,
> for a smooth list to be sent.
> I tried to send a button message but it didn't send even there was no error message from the system, it looks normal but the message is not sent, I use personal whatsapp.
> 
> responses:
> 
> ```
> Message {
>   mediaKey: undefined,
>   id:
>    { fromMe: true,
>      remote:
>       { server: 'c.us',
>         user: '62xxxx',
>         _serialized: '62xxxx@c.us' },
>      id: '3EB0CB3BE1BB703750DD',
>      _serialized: 'true_628xxxx@c.us_3EB0CB3BE1BB703750DD' },
>   ack: 0,
>   hasMedia: false,
>   body: 'ini test body button',
>   type: 'chat',
>   timestamp: 1628296215,
>   from: '62xxxx@c.us',
>   to: '62xxxx@c.us',
>   author: undefined,
>   deviceType: 'web',
>   isForwarded: false,
>   forwardingScore: 0,
>   isStatus: undefined,
>   isStarred: false,
>   broadcast: undefined,
>   fromMe: true,
>   hasQuotedMsg: false,
>   location: undefined,
>   vCards: [],
>   inviteV4: undefined,
>   mentionedIds: [],
>   orderId: undefined,
>   token: undefined,
>   title: 'ini test title',
>   links: undefined,
>   dynamicReplyButtons:
>    [ { buttonId: 'ySE9Te', buttonText: [Object], type: 1 },
>      { buttonId: 'VkcgC7', buttonText: [Object], type: 1 },
>      { buttonId: 'JiwHP8', buttonText: [Object], type: 1 } ] }
> ```
> 
> please give directions so that the message button can be sent. thank you

2021-08-08 04:32 UTC, tuyuribr commented
> 
> 
> @tuyuribr
> 
> yes. but the button doesn't work on the standard account I have.
@0xT01 
Try again but with the new commit ( c3becb8 ), get the pr again

2021-08-08 15:53 UTC, Gimenz approved these changes

2021-08-10 00:43 UTC, ricocrivelli commented
> 
> 
> > @tuyuribr
> > yes. but the button doesn't work on the standard account I have.
> > @0xT01
> > Try again but with the new commit ( [c3becb8](https://github.com/pedroslopez/whatsapp-web.js/commit/c3becb8ec0940bdfce50f9abb3d6b89911d8504d) ), get the pr again

Its working now!!

2021-08-17 18:22 UTC, 0xT01 commented
**WhatsApp** has a new feature. only displays once for the image.?
can this feature be added here?

![WhatsApp Image 2021-08-18 at 01 18 47](https://user-images.githubusercontent.com/87315860/129779846-43732f51-a261-4c0a-99df-bc2e80ba9127.jpeg)
![WhatsApp Image 2021-08-18 at 01 18 48](https://user-images.githubusercontent.com/87315860/129779885-33954211-a55f-4190-a79f-4084b7652bb5.jpeg)
![WhatsApp Image 2021-08-18 at 01 18 49](https://user-images.githubusercontent.com/87315860/129779920-a42c50e8-2ab5-4b6d-8892-7e9a7e832b23.jpeg)
![WhatsApp Image 2021-08-18 at 01 18 49 (1)](https://user-images.githubusercontent.com/87315860/129779972-59db17e8-cd52-40ac-9be4-313ed6fb747d.jpeg)
![WhatsApp Image 2021-08-18 at 01 18 50](https://user-images.githubusercontent.com/87315860/129779990-949b8885-d1da-4769-a43f-e2fe73a641ff.jpeg)

2021-08-17 19:13 UTC, tuyuribr commented
> 
> 
> **WhatsApp** has a new feature. only displays once for the image.?
> can this feature be added here?
> 

In the lib: Yes
in this PR: No
Hotel? Triv@g0

2021-08-20 19:21 UTC, Spooder9 commented
Hi, it doesn't work for me, what am I doing wrong?
![Captura de pantalla de 2021-08-20 09-20-46](https://user-images.githubusercontent.com/63208071/130283559-890cc99e-04c0-45f9-b882-68d9681fd6cc.png)

2021-08-20 20:33 UTC, ricocrivelli commented
> 
> 
> Hi, it doesn't work for me, what am I doing wrong?
> ![Captura de pantalla de 2021-08-20 09-20-46](https://user-images.githubusercontent.com/63208071/130283559-890cc99e-04c0-45f9-b882-68d9681fd6cc.png)

You probably forgot to import the class at the beginning of the code.

2021-08-20 21:02 UTC, Spooder9 commented
> > Hi, it doesn't work for me, what am I doing wrong?
> > ![Captura de pantalla de 2021-08-20 09-20-46](https://user-images.githubusercontent.com/63208071/130283559-890cc99e-04c0-45f9-b882-68d9681fd6cc.png)
> 
> You probably forgot to import the class at the beginning of the code.
> 
> `const { ClientInfo, Message, MessageMedia, Contact, Location, GroupNotification , Label, Call, Buttons, List} = require('./structures');`

I have already imported the module as you indicate but it still does not work.
![Captura de pantalla de 2021-08-20 11-00-25](https://user-images.githubusercontent.com/63208071/130293023-3e1732dd-f5ae-45f4-acd1-974e2d0d81fa.png)

2021-08-20 21:03 UTC, Spooder9 commented
![Captura de pantalla de 2021-08-20 11-03-10](https://user-images.githubusercontent.com/63208071/130293070-8fa3c005-e112-473c-8ae5-82998149c2ba.png)

2021-08-20 21:22 UTC, ricocrivelli commented
> 
> 
> ![Captura de pantalla de 2021-08-20 11-03-10](https://user-images.githubusercontent.com/63208071/130293070-8fa3c005-e112-473c-8ae5-82998149c2ba.png)

Looks like you are using the production source. This is a pull request, so the new source isn't in the main files. You can clone the branch https://github.com/tuyuribr/whatsapp-web.js/tree/patch-6 ou see the modified files and create by your own https://github.com/pedroslopez/whatsapp-web.js/pull/756/files

2021-08-21 07:38 UTC, Scoooolz commented
How i can fix this?

(node:23484) UnhandledPromiseRejectionWarning: TypeError: Buttons is not a constructor
    at Client.<anonymous> (C:\Users\User\whatsapp-api\app.js:70:26)
    at Client.emit (events.js:375:28)
    at C:\Users\User\whatsapp-api\node_modules\whatsapp-web.js\src\Client.js:251:18
    at Page._onBindingCalled (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:980:62)
    at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:159:60
    at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onMessage (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:234:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

2021-08-21 12:28 UTC, ricocrivelli commented
> 
> 
> How i can fix this?
> 
> (node:23484) UnhandledPromiseRejectionWarning: TypeError: Buttons is not a constructor
> at Client. (C:\Users\User\whatsapp-api\app.js:70:26)
> at Client.emit (events.js:375:28)
> at C:\Users\User\whatsapp-api\node_modules\whatsapp-web.js\src\Client.js:251:18
> at Page._onBindingCalled (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:980:62)
> at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:159:60
> at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
> at Array.map ()
> at Object.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
> at CDPSession.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
> at CDPSession._onMessage (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:234:18)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:23484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:23484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Take a look at my previous comment, maybe it can help you.  https://github.com/pedroslopez/whatsapp-web.js/pull/756#issuecomment-902965071

2021-08-22 05:50 UTC, Scoooolz commented
> > How i can fix this?
> > (node:23484) UnhandledPromiseRejectionWarning: TypeError: Buttons is not a constructor
> > at Client. (C:\Users\User\whatsapp-api\app.js:70:26)
> > at Client.emit (events.js:375:28)
> > at C:\Users\User\whatsapp-api\node_modules\whatsapp-web.js\src\Client.js:251:18
> > at Page._onBindingCalled (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:980:62)
> > at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:159:60
> > at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
> > at Array.map ()
> > at Object.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
> > at CDPSession.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
> > at CDPSession._onMessage (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:234:18)
> > (Use `node --trace-warnings ...` to show where the warning was created)
> > (node:23484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> > (node:23484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> Take a look at my previous comment, maybe it can help you. [#756 (comment)](https://github.com/pedroslopez/whatsapp-web.js/pull/756#issuecomment-902965071)

Same.

(node:30828) UnhandledPromiseRejectionWarning: TypeError: Buttons is not a constructor
    at Client.<anonymous> (C:\Users\User\whatsapp-api\app.js:73:26)
    at Client.emit (events.js:375:28)
    at C:\Users\User\whatsapp-api\node_modules\whatsapp-web.js\src\Client.js:251:18
    at Page._onBindingCalled (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:980:62)
    at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:159:60
    at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onMessage (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:234:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Are i wrong?

In const
const { Client } = require('whatsapp-web.js');
const { Buttons } = require('./node_modules/whatsapp-web.js/src/structures')
const express = require('express');
const io = require('socket.io')
const qrcode = require('qrcode-terminal');
const fs = require('fs');

In Commands
client.on('message', async msg => {

        if(msg.body === '!quiz') {
            let button = new Buttons('Button body',[{body:'bt1'},{body:'bt2'},{body:'bt3'}],'title','footer');
            client.sendMessage(msg.from, button);
});

2021-08-22 05:59 UTC, Scoooolz commented
> Take a look at my previous comment, maybe it can help you. [#756 (comment)](https://github.com/pedroslopez/whatsapp-web.js/pull/756#issuecomment-902965071)

Same.

(node:30828) UnhandledPromiseRejectionWarning: TypeError: Buttons is not a constructor
    at Client.<anonymous> (C:\Users\User\whatsapp-api\app.js:73:26)
    at Client.emit (events.js:375:28)
    at C:\Users\User\whatsapp-api\node_modules\whatsapp-web.js\src\Client.js:251:18
    at Page._onBindingCalled (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:980:62)
    at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:159:60
    at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onMessage (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:234:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Are i wrong?

In const

const { Client } = require('whatsapp-web.js');
const { Buttons } = require('./node_modules/whatsapp-web.js/src/structures')
const express = require('express');
const io = require('socket.io')
const qrcode = require('qrcode-terminal');
const fs = require('fs');


In Commands

client.on('message',`` async msg => {
        if(msg.body === '!quiz') {
            let button = new Buttons('Button body',[{body:'bt1'},{body:'bt2'},{body:'bt3'}],'title','footer');
            client.sendMessage(msg.from, button);
});

2021-08-23 16:18 UTC, PurpShell commented
> How can I help to test this functionality?

to install & therefore test it: 

you have to npm install it via a different route
npm i github:tuyuribr/whatsapp-web.js#patch-6

btw this is how i got #patch-6 at the end:
![image](https://user-images.githubusercontent.com/52720753/130482064-602cc141-1656-4ca7-aada-99d6939df283.png)

2021-08-23 16:19 UTC, PurpShell commented
> > Take a look at my previous comment, maybe it can help you. [#756 (comment)](https://github.com/pedroslopez/whatsapp-web.js/pull/756#issuecomment-902965071)
> 
> Same.
> 
> (node:30828) UnhandledPromiseRejectionWarning: TypeError: Buttons is not a constructor
> at Client. (C:\Users\User\whatsapp-api\app.js:73:26)
> at Client.emit (events.js:375:28)
> at C:\Users\User\whatsapp-api\node_modules\whatsapp-web.js\src\Client.js:251:18
> at Page._onBindingCalled (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:980:62)
> at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:159:60
> at C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
> at Array.map ()
> at Object.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
> at CDPSession.emit (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
> at CDPSession._onMessage (C:\Users\User\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:234:18)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:30828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:30828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> Are i wrong?
> 
> In const
> 
> const { Client } = require('whatsapp-web.js');
> const { Buttons } = require('./node_modules/whatsapp-web.js/src/structures')
> const express = require('express');
> const io = require('socket.io')
> const qrcode = require('qrcode-terminal');
> const fs = require('fs');
> 
> In Commands
> 
> client.on('message',`` async msg => {
> if(msg.body === '!quiz') {
> let button = new Buttons('Button body',[{body:'bt1'},{body:'bt2'},{body:'bt3'}],'title','footer');
> client.sendMessage(msg.from, button);
> });

yeah you are: 
In const: 
```diff
+ const { Client, Buttons } = require('whatsapp-web.js');
- const { Buttons } = require('./node_modules/whatsapp-web.js/src/structures')
const express = require('express');
const io = require('socket.io')
const qrcode = require('qrcode-terminal');
const fs = require('fs');
```

2021-08-23 16:47 UTC, Spooder9 commented
> > ![Captura de pantalla de 2021-08-20 11-03-10](https://user-images.githubusercontent.com/63208071/130293070-8fa3c005-e112-473c-8ae5-82998149c2ba.png)
> 
> Looks like you are using the production source. This is a pull request, so the new source isn't in the main files. You can clone the branch https://github.com/tuyuribr/whatsapp-web.js/tree/patch-6 ou see the modified files and create by your own https://github.com/pedroslopez/whatsapp-web.js/pull/756/files

Gracias

2021-09-01 15:36 UTC, renjop commented
> 
> 
> > It seems that the most recent WhatsApp version (2.2134.9) broke the sending of this buttons:
> > `{ "message": "Msg", "name": "ModelCreateError", "stack": "ModelCreateError: Msg\n at new i (https://web.whatsapp.com/bootstrap_qr.abbc2ea8366e2cd9a145.js:2:403072)\n at new k (https://web.whatsapp.com/bootstrap_qr.abbc2ea8366e2cd9a145.js:56:209667)\n at https://web.whatsapp.com/bootstrap_qr.abbc2ea8366e2cd9a145.js:2:470293\n at V (https://web.whatsapp.com/bootstrap_qr.abbc2ea8366e2cd9a145.js:2:373738)\n at MutationObserver.K (https://web.whatsapp.com/bootstrap_qr.abbc2ea8366e2cd9a145.js:2:373319)",`
> 
> Hmmm it's working here, are you using whatsapp-web.js@1.14.1 ?

Yep, I'm using the latest whatsapp-web.js@1.41.1. Before the WhatsApp update it was working perfectly, This error seems to be an internal "error" from WhatsApp not necessarily from the whatsapp-web.js library.

2021-09-08 02:39 UTC, makanSukros commented
Not Working on MD Version @PurpShell

2021-09-08 04:36 UTC, makanSukros commented
> Not Working on MD Version @PurpShell

vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34 TypeError: Cannot read properties of undefined (reading 'length')
    at bootstrap_main.e39859bf8358eb1e7271.js:13
    at Array.some (<anonymous>)
    at t.default (bootstrap_main.e39859bf8358eb1e7271.js:13)
    at ia (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at Hs (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at Pu (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at Eu (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at Su (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at mu (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34

2021-09-08 04:37 UTC, makanSukros commented
> Not Working on MD Version @PurpShell

```
vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34 TypeError: Cannot read properties of undefined (reading 'length')
    at bootstrap_main.e39859bf8358eb1e7271.js:13
    at Array.some (<anonymous>)
    at t.default (bootstrap_main.e39859bf8358eb1e7271.js:13)
    at ia (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at Hs (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at Pu (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at Eu (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at Su (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at mu (vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34)
    at vendor1~bootstrap_qr.8d5b7620b726968ba154.js:34
```

2021-09-09 00:42 UTC, jmas005 commented
Can I identify the custom ID returned from a Message of type List?

2021-09-11 04:49 UTC, rmaafs commented
I tested it for two weeks and I don't have any problem.
Tested on Android and iOS. Nice work!

2021-09-11 04:51 UTC, makanSukros commented
> I tested it for two weeks and I don't have any problem.
> Tested on Android and iOS. Nice work!

Problem only for Beta MultiDevices

2021-09-11 23:21 UTC, jmas005 approved these changes
Oh, I spent some time testing some things to see if I could come up with a solution, but I wasn't able to come up with this excellent solution

2021-09-13 20:21 UTC, Aliyss approved these changes
lgtm

2021-09-13 20:59 UTC, PurpShell commented
Merge time

2021-09-13 21:06 UTC, merged

2021-09-16 11:40 UTC, Fibonacci-Solucoes-Ageis commented
When i sent a button message the Whatsapp Web chat throws the following exception.

![image](https://user-images.githubusercontent.com/555425/133605645-e8d5d817-3918-4e92-996d-b639ea4be751.png)

2021-09-16 11:45 UTC, Goomer2 commented
When I send a Button Message the Whatsapp Web Chat throws  the following exception.

![image](https://user-images.githubusercontent.com/90841347/133606338-9b7e1544-83a2-447a-9c3d-a49fa56804e4.png)

2021-09-16 13:27 UTC, tuyuribr commented
@Goomer2 , could you send us some code?
Are you using standard wa or biz?


Image for reference:
![image](https://user-images.githubusercontent.com/45042245/133620579-e2219082-04c1-4a0a-afd2-7cfab7172eee.png)

2021-09-16 13:53 UTC, Goomer2 commented
> @Goomer2 , could you send us some code?
> Are you using standard wa or biz?
> 
> Image for reference:
> ![image](https://user-images.githubusercontent.com/45042245/133620579-e2219082-04c1-4a0a-afd2-7cfab7172eee.png)

I'm using biz.

```
const { Client, Buttons, List } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');

const client = new Client({puppeteer: {headless: false}});

client.on('qr', (qr) => {
  // Generate and scan this code with your phone
  console.log('QR RECEIVED', qr);
  qrcode.generate(qr, {small: true});
});

client.on('ready', () => {
  console.log('Client is ready!');

  let button = new Buttons('Button body', [{body:'Sim'},{body:'Não'},{body:'Não enviar mais'}],'title','footer');
  client.sendMessage('xxxxx@c.us', button);
});

client.on('message', msg => {
  if (msg.body == '!ping') {
    msg.reply('pong');
  }
});

client.initialize();
```

The error is on Whatsapp Web.

2021-12-05 23:32 UTC, tinyCoder32 commented
> When I send a Button Message the Whatsapp Web Chat throws the following exception.
> 
> ![image](https://user-images.githubusercontent.com/90841347/133606338-9b7e1544-83a2-447a-9c3d-a49fa56804e4.png)

Is there any fix for this yet? It's pretty annoying 😓