Allow a chat to be muted indefinitely
pedroslopez/whatsapp-web.js pull request #849
Opened 2021-08-23 17:15 UTC by PurpShell

2021-08-26 18:21 UTC, tuyuribr approved these changes
LGTM!

2021-09-28 03:52 UTC, pedroslopez requested changes
Thanks for adding this! I think we still need to divide by 1000

![image](https://user-images.githubusercontent.com/4368928/135020535-64086fdc-fdd2-46f7-93b9-d2c165f81aa5.png)

2021-09-29 19:35 UTC, PurpShell commented on src/Client.js
> -        }, chatId, unmuteDate.getTime() / 1000);
hmm ok

2021-09-29 19:39 UTC, Kristrue commented
I would love to know more about the conversation and yes I agree to mute

On Sun, Sep 26, 2021, 2:38 PM stale[bot] ***@***.***> wrote:

> This issue has been automatically marked as stale because it has not had
> recent activity. It will be closed if no further activity occurs. Thank you
> for your contributions.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pedroslopez/whatsapp-web.js/pull/849#issuecomment-927350712>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVXWOWVVRKFY2ZCF3Z7SICDUD5SBZANCNFSM5CVATT2A>
> .
>

2021-09-30 14:57 UTC, PurpShell commented
> Thanks for adding this! I think we still need to divide by 1000
> 
> ![image](https://user-images.githubusercontent.com/4368928/135020535-64086fdc-fdd2-46f7-93b9-d2c165f81aa5.png)
> 

All done

2021-10-30 03:24 UTC, pedroslopez approved these changes

2021-10-30 03:24 UTC, merged